import { db } from '@/db';
import { auditLogs } from '@/db/schema';

async function main() {
    const sampleAuditLogs = [
        {
            timestamp: new Date('2024-11-15T09:15:00Z').toISOString(),
            patientId: 12,
            patientName: 'Sarah Johnson',
            changedBy: 'Dr. Smith',
            fieldsChanged: ['phone', 'email'],
            oldValue: { phone: '+27 83 456 7890', email: 'sarah.old@gmail.com' },
            newValue: { phone: '+27 84 123 4567', email: 'sarah.johnson@gmail.com' },
            reason: 'Patient requested update',
            metadata: { ipAddress: '192.168.1.101', userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', sessionId: 'sess_123abc' },
            createdAt: new Date('2024-11-15T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-11-15T09:15:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-14T14:30:00Z').toISOString(),
            patientId: 25,
            patientName: 'Michael Chen',
            changedBy: 'Admin Mary',
            fieldsChanged: ['medicalAid', 'medicalAidNumber'],
            oldValue: { medicalAid: 'Discovery Health', medicalAidNumber: 'DH123456789' },
            newValue: { medicalAid: 'Momentum Health', medicalAidNumber: 'MH987654321' },
            reason: 'Insurance plan change',
            metadata: { ipAddress: '10.0.0.25', userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36', action: 'bulk_update' },
            createdAt: new Date('2024-11-14T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-14T14:30:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-13T11:45:00Z').toISOString(),
            patientId: 8,
            patientName: 'Linda Williams',
            changedBy: 'Nurse Johnson',
            fieldsChanged: ['address', 'city', 'postalCode'],
            oldValue: { address: '123 Main Street', city: 'Cape Town', postalCode: '8001' },
            newValue: { address: '456 Oak Avenue', city: 'Stellenbosch', postalCode: '7600' },
            reason: 'Patient moved to new address',
            metadata: null,
            createdAt: new Date('2024-11-13T11:45:00Z').toISOString(),
            updatedAt: new Date('2024-11-13T11:45:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-12T16:20:00Z').toISOString(),
            patientId: 33,
            patientName: 'David Miller',
            changedBy: 'Reception Desk',
            fieldsChanged: ['saIdNumber'],
            oldValue: { saIdNumber: '8501015800085' },
            newValue: { saIdNumber: '8501015800086' },
            reason: 'Incorrect information corrected',
            metadata: { ipAddress: '192.168.1.50', correctedBy: 'reception_staff', verificationMethod: 'id_document_scan' },
            createdAt: new Date('2024-11-12T16:20:00Z').toISOString(),
            updatedAt: new Date('2024-11-12T16:20:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-11T10:10:00Z').toISOString(),
            patientId: 45,
            patientName: 'Emma Thompson',
            changedBy: 'System Update',
            fieldsChanged: ['active'],
            oldValue: { active: true },
            newValue: { active: false },
            reason: null,
            metadata: { automated: true, trigger: 'inactivity_policy', lastVisit: '2024-05-15' },
            createdAt: new Date('2024-11-11T10:10:00Z').toISOString(),
            updatedAt: new Date('2024-11-11T10:10:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-10T13:55:00Z').toISOString(),
            patientId: 17,
            patientName: 'James Anderson',
            changedBy: 'Dr. Patel',
            fieldsChanged: ['emergencyContactName', 'emergencyContactPhone'],
            oldValue: { emergencyContactName: 'Mary Anderson', emergencyContactPhone: '+27 82 555 1234' },
            newValue: { emergencyContactName: 'John Anderson', emergencyContactPhone: '+27 83 666 5678' },
            reason: 'Emergency contact updated',
            metadata: { ipAddress: '172.16.0.10', sessionDuration: '45min' },
            createdAt: new Date('2024-11-10T13:55:00Z').toISOString(),
            updatedAt: new Date('2024-11-10T13:55:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-09T08:30:00Z').toISOString(),
            patientId: 52,
            patientName: 'Rachel Green',
            changedBy: 'Admin Mary',
            fieldsChanged: ['firstName', 'lastName'],
            oldValue: { firstName: 'Rachael', lastName: 'Greene' },
            newValue: { firstName: 'Rachel', lastName: 'Green' },
            reason: 'Name spelling correction',
            metadata: { ipAddress: '10.0.0.25', documentRef: 'ID_20241109_001' },
            createdAt: new Date('2024-11-09T08:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-09T08:30:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-08T15:40:00Z').toISOString(),
            patientId: 3,
            patientName: 'Robert Davis',
            changedBy: 'Nurse Johnson',
            fieldsChanged: ['phone'],
            oldValue: { phone: '+27 81 123 4567' },
            newValue: { phone: '+27 82 987 6543' },
            reason: 'Phone number changed',
            metadata: { ipAddress: '192.168.1.102', verificationCode: 'sent_sms' },
            createdAt: new Date('2024-11-08T15:40:00Z').toISOString(),
            updatedAt: new Date('2024-11-08T15:40:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-07T12:15:00Z').toISOString(),
            patientId: 29,
            patientName: 'Sophie Wilson',
            changedBy: 'Dr. Smith',
            fieldsChanged: ['idType', 'passportNumber', 'passportCountry'],
            oldValue: { idType: 'sa_id', passportNumber: null, passportCountry: null },
            newValue: { idType: 'passport', passportNumber: 'GB123456789', passportCountry: 'United Kingdom' },
            reason: 'Document verification',
            metadata: { ipAddress: '192.168.1.101', documentScanned: true, verificationDate: '2024-11-07' },
            createdAt: new Date('2024-11-07T12:15:00Z').toISOString(),
            updatedAt: new Date('2024-11-07T12:15:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-06T09:25:00Z').toISOString(),
            patientId: 41,
            patientName: 'Peter Brown',
            changedBy: 'Reception Desk',
            fieldsChanged: ['email'],
            oldValue: { email: null },
            newValue: { email: 'peter.brown@outlook.com' },
            reason: 'Patient provided email address',
            metadata: null,
            createdAt: new Date('2024-11-06T09:25:00Z').toISOString(),
            updatedAt: new Date('2024-11-06T09:25:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-05T14:50:00Z').toISOString(),
            patientId: 16,
            patientName: 'Maria Garcia',
            changedBy: 'Admin Mary',
            fieldsChanged: ['medicalAidNumber'],
            oldValue: { medicalAidNumber: 'MED001234' },
            newValue: { medicalAidNumber: 'MED001235' },
            reason: 'Medical aid number correction',
            metadata: { ipAddress: '10.0.0.25', source: 'medical_aid_verification' },
            createdAt: new Date('2024-11-05T14:50:00Z').toISOString(),
            updatedAt: new Date('2024-11-05T14:50:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-04T11:35:00Z').toISOString(),
            patientId: 58,
            patientName: 'Alan Taylor',
            changedBy: 'Dr. Patel',
            fieldsChanged: ['active'],
            oldValue: { active: false },
            newValue: { active: true },
            reason: 'Patient reactivation requested',
            metadata: { ipAddress: '172.16.0.10', reactivationReason: 'new_treatment_plan' },
            createdAt: new Date('2024-11-04T11:35:00Z').toISOString(),
            updatedAt: new Date('2024-11-04T11:35:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-03T16:10:00Z').toISOString(),
            patientId: 7,
            patientName: 'Jennifer Lee',
            changedBy: 'Nurse Johnson',
            fieldsChanged: ['province'],
            oldValue: { province: 'Western Cape' },
            newValue: { province: 'Gauteng' },
            reason: 'Patient relocated',
            metadata: { ipAddress: '192.168.1.102', updateSource: 'patient_form' },
            createdAt: new Date('2024-11-03T16:10:00Z').toISOString(),
            updatedAt: new Date('2024-11-03T16:10:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-02T10:45:00Z').toISOString(),
            patientId: 22,
            patientName: 'Christopher Moore',
            changedBy: 'System Update',
            fieldsChanged: ['updatedAt'],
            oldValue: { updatedAt: '2024-10-15T10:30:00Z' },
            newValue: { updatedAt: '2024-11-02T10:45:00Z' },
            reason: null,
            metadata: { automated: true, trigger: 'scheduled_maintenance' },
            createdAt: new Date('2024-11-02T10:45:00Z').toISOString(),
            updatedAt: new Date('2024-11-02T10:45:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-11-01T13:20:00Z').toISOString(),
            patientId: 35,
            patientName: 'Amanda White',
            changedBy: 'Dr. Smith',
            fieldsChanged: ['emergencyContactRelationship'],
            oldValue: { emergencyContactRelationship: 'Spouse' },
            newValue: { emergencyContactRelationship: 'Sister' },
            reason: 'Emergency contact relationship updated',
            metadata: { ipAddress: '192.168.1.101', sessionType: 'patient_update' },
            createdAt: new Date('2024-11-01T13:20:00Z').toISOString(),
            updatedAt: new Date('2024-11-01T13:20:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-31T15:30:00Z').toISOString(),
            patientId: 49,
            patientName: 'Kevin Martinez',
            changedBy: 'Reception Desk',
            fieldsChanged: ['phone', 'address'],
            oldValue: { phone: '+27 84 111 2222', address: '789 Elm Street' },
            newValue: { phone: '+27 85 333 4444', address: '321 Pine Road' },
            reason: 'Patient information update',
            metadata: { ipAddress: '192.168.1.50', batchUpdate: false },
            createdAt: new Date('2024-10-31T15:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-31T15:30:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-30T09:15:00Z').toISOString(),
            patientId: 14,
            patientName: 'Lisa Jackson',
            changedBy: 'Admin Mary',
            fieldsChanged: ['email'],
            oldValue: { email: 'lisa.jackson@old-domain.com' },
            newValue: { email: 'lisa.jackson@newdomain.com' },
            reason: 'Email domain change',
            metadata: { ipAddress: '10.0.0.25', emailVerified: true },
            createdAt: new Date('2024-10-30T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-30T09:15:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-29T14:45:00Z').toISOString(),
            patientId: 37,
            patientName: 'Daniel Harris',
            changedBy: 'Dr. Patel',
            fieldsChanged: ['medicalAid'],
            oldValue: { medicalAid: 'Bonitas Medical Fund' },
            newValue: { medicalAid: 'Medihelp' },
            reason: 'Medical aid scheme change',
            metadata: { ipAddress: '172.16.0.10', previousSchemeActive: false },
            createdAt: new Date('2024-10-29T14:45:00Z').toISOString(),
            updatedAt: new Date('2024-10-29T14:45:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-28T11:20:00Z').toISOString(),
            patientId: 60,
            patientName: 'Nicole Clark',
            changedBy: 'Nurse Johnson',
            fieldsChanged: ['saIdNumber'],
            oldValue: { saIdNumber: '9203155432108' },
            newValue: { saIdNumber: '9203155432109' },
            reason: 'ID number verification correction',
            metadata: { ipAddress: '192.168.1.102', verificationMethod: 'manual_check' },
            createdAt: new Date('2024-10-28T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-28T11:20:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-27T16:55:00Z').toISOString(),
            patientId: 11,
            patientName: 'Brian Rodriguez',
            changedBy: 'System Update',
            fieldsChanged: ['active'],
            oldValue: { active: true },
            newValue: { active: false },
            reason: null,
            metadata: { automated: true, trigger: 'data_cleanup', lastActivity: '2024-06-15' },
            createdAt: new Date('2024-10-27T16:55:00Z').toISOString(),
            updatedAt: new Date('2024-10-27T16:55:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-26T08:40:00Z').toISOString(),
            patientId: 28,
            patientName: 'Rebecca Lewis',
            changedBy: 'Reception Desk',
            fieldsChanged: ['city', 'postalCode'],
            oldValue: { city: 'Johannesburg', postalCode: '2001' },
            newValue: { city: 'Pretoria', postalCode: '0001' },
            reason: 'Address update - patient moved',
            metadata: null,
            createdAt: new Date('2024-10-26T08:40:00Z').toISOString(),
            updatedAt: new Date('2024-10-26T08:40:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-25T12:30:00Z').toISOString(),
            patientId: 43,
            patientName: 'Gregory Walker',
            changedBy: 'Dr. Smith',
            fieldsChanged: ['passportNumber'],
            oldValue: { passportNumber: 'US987654321' },
            newValue: { passportNumber: 'US123456789' },
            reason: 'Passport renewal update',
            metadata: { ipAddress: '192.168.1.101', documentExpiry: '2029-10-25' },
            createdAt: new Date('2024-10-25T12:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-25T12:30:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-24T15:15:00Z').toISOString(),
            patientId: 5,
            patientName: 'Helen Young',
            changedBy: 'Admin Mary',
            fieldsChanged: ['emergencyContactPhone'],
            oldValue: { emergencyContactPhone: '+27 82 777 8888' },
            newValue: { emergencyContactPhone: '+27 83 999 1111' },
            reason: 'Emergency contact phone updated',
            metadata: { ipAddress: '10.0.0.25', contactVerified: true },
            createdAt: new Date('2024-10-24T15:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-24T15:15:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-23T10:50:00Z').toISOString(),
            patientId: 56,
            patientName: 'Steven King',
            changedBy: 'Nurse Johnson',
            fieldsChanged: ['phone', 'email'],
            oldValue: { phone: '+27 84 555 6666', email: 'steven.old@yahoo.com' },
            newValue: { phone: '+27 85 777 8888', email: 'steven.king@gmail.com' },
            reason: 'Contact information update',
            metadata: { ipAddress: '192.168.1.102', updateReason: 'patient_request' },
            createdAt: new Date('2024-10-23T10:50:00Z').toISOString(),
            updatedAt: new Date('2024-10-23T10:50:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-22T14:25:00Z').toISOString(),
            patientId: 19,
            patientName: 'Dorothy Hall',
            changedBy: 'Dr. Patel',
            fieldsChanged: ['medicalAidNumber'],
            oldValue: { medicalAidNumber: 'GEM456789' },
            newValue: { medicalAidNumber: 'GEM987654' },
            reason: 'Medical aid membership number updated',
            metadata: { ipAddress: '172.16.0.10', verificationSource: 'medical_aid_portal' },
            createdAt: new Date('2024-10-22T14:25:00Z').toISOString(),
            updatedAt: new Date('2024-10-22T14:25:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-21T09:35:00Z').toISOString(),
            patientId: 32,
            patientName: 'Paul Allen',
            changedBy: 'Reception Desk',
            fieldsChanged: ['address'],
            oldValue: { address: '159 Broadway Avenue' },
            newValue: { address: '753 Victoria Street' },
            reason: 'Residential address change',
            metadata: { ipAddress: '192.168.1.50', moveDate: '2024-10-15' },
            createdAt: new Date('2024-10-21T09:35:00Z').toISOString(),
            updatedAt: new Date('2024-10-21T09:35:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-20T13:10:00Z').toISOString(),
            patientId: 47,
            patientName: 'Sandra Wright',
            changedBy: 'System Update',
            fieldsChanged: ['updatedAt'],
            oldValue: { updatedAt: '2024-09-20T08:00:00Z' },
            newValue: { updatedAt: '2024-10-20T13:10:00Z' },
            reason: null,
            metadata: { automated: true, trigger: 'monthly_update_batch' },
            createdAt: new Date('2024-10-20T13:10:00Z').toISOString(),
            updatedAt: new Date('2024-10-20T13:10:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-19T16:45:00Z').toISOString(),
            patientId: 9,
            patientName: 'Kenneth Scott',
            changedBy: 'Dr. Smith',
            fieldsChanged: ['active'],
            oldValue: { active: false },
            newValue: { active: true },
            reason: 'Patient account reactivated',
            metadata: { ipAddress: '192.168.1.101', reactivationDate: '2024-10-19' },
            createdAt: new Date('2024-10-19T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-10-19T16:45:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-18T11:20:00Z').toISOString(),
            patientId: 54,
            patientName: 'Betty Green',
            changedBy: 'Admin Mary',
            fieldsChanged: ['firstName'],
            oldValue: { firstName: 'Elizabeth' },
            newValue: { firstName: 'Betty' },
            reason: 'Preferred name update',
            metadata: { ipAddress: '10.0.0.25', requestedBy: 'patient' },
            createdAt: new Date('2024-10-18T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-18T11:20:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-17T08:55:00Z').toISOString(),
            patientId: 26,
            patientName: 'Frank Adams',
            changedBy: 'Nurse Johnson',
            fieldsChanged: ['passportCountry'],
            oldValue: { passportCountry: 'Canada' },
            newValue: { passportCountry: 'Australia' },
            reason: 'Passport country correction',
            metadata: { ipAddress: '192.168.1.102', documentVerified: true },
            createdAt: new Date('2024-10-17T08:55:00Z').toISOString(),
            updatedAt: new Date('2024-10-17T08:55:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-16T15:40:00Z').toISOString(),
            patientId: 38,
            patientName: 'Carol Baker',
            changedBy: 'Reception Desk',
            fieldsChanged: ['email', 'phone'],
            oldValue: { email: 'carol.b@hotmail.com', phone: '+27 81 222 3333' },
            newValue: { email: 'carol.baker@outlook.com', phone: '+27 82 444 5555' },
            reason: 'Contact details updated by patient',
            metadata: null,
            createdAt: new Date('2024-10-16T15:40:00Z').toISOString(),
            updatedAt: new Date('2024-10-16T15:40:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-15T12:25:00Z').toISOString(),
            patientId: 13,
            patientName: 'Larry Nelson',
            changedBy: 'Dr. Patel',
            fieldsChanged: ['medicalAid', 'medicalAidNumber'],
            oldValue: { medicalAid: 'Fedhealth', medicalAidNumber: 'FH111222' },
            newValue: { medicalAid: 'GEMS', medicalAidNumber: 'GMS333444' },
            reason: 'Medical aid scheme transfer',
            metadata: { ipAddress: '172.16.0.10', transferDate: '2024-10-01' },
            createdAt: new Date('2024-10-15T12:25:00Z').toISOString(),
            updatedAt: new Date('2024-10-15T12:25:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-14T10:30:00Z').toISOString(),
            patientId: 51,
            patientName: 'Donna Carter',
            changedBy: 'System Update',
            fieldsChanged: ['active'],
            oldValue: { active: true },
            newValue: { active: false },
            reason: null,
            metadata: { automated: true, trigger: 'inactive_patient_policy', lastVisit: '2024-04-10' },
            createdAt: new Date('2024-10-14T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-14T10:30:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-13T14:15:00Z').toISOString(),
            patientId: 21,
            patientName: 'Roger Mitchell',
            changedBy: 'Admin Mary',
            fieldsChanged: ['emergencyContactName', 'emergencyContactRelationship'],
            oldValue: { emergencyContactName: 'Susan Mitchell', emergencyContactRelationship: 'Wife' },
            newValue: { emergencyContactName: 'Tom Mitchell', emergencyContactRelationship: 'Brother' },
            reason: 'Emergency contact changed',
            metadata: { ipAddress: '10.0.0.25', contactChangeReason: 'family_circumstances' },
            createdAt: new Date('2024-10-13T14:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-13T14:15:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-12T09:00:00Z').toISOString(),
            patientId: 44,
            patientName: 'Ruth Perez',
            changedBy: 'Nurse Johnson',
            fieldsChanged: ['saIdNumber'],
            oldValue: { saIdNumber: '8712314567890' },
            newValue: { saIdNumber: '8712314567891' },
            reason: 'ID number digit correction',
            metadata: { ipAddress: '192.168.1.102', verificationMethod: 'id_document_check' },
            createdAt: new Date('2024-10-12T09:00:00Z').toISOString(),
            updatedAt: new Date('2024-10-12T09:00:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-11T16:30:00Z').toISOString(),
            patientId: 6,
            patientName: 'Gary Roberts',
            changedBy: 'Dr. Smith',
            fieldsChanged: ['province', 'city'],
            oldValue: { province: 'KwaZulu-Natal', city: 'Durban' },
            newValue: { province: 'Western Cape', city: 'Cape Town' },
            reason: 'Patient relocated to different province',
            metadata: { ipAddress: '192.168.1.101', relocationDate: '2024-10-01' },
            createdAt: new Date('2024-10-11T16:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-11T16:30:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-10T13:45:00Z').toISOString(),
            patientId: 59,
            patientName: 'Sharon Turner',
            changedBy: 'Reception Desk',
            fieldsChanged: ['phone'],
            oldValue: { phone: '+27 83 888 9999' },
            newValue: { phone: '+27 84 111 2222' },
            reason: 'New phone number provided',
            metadata: { ipAddress: '192.168.1.50', phoneType: 'mobile' },
            createdAt: new Date('2024-10-10T13:45:00Z').toISOString(),
            updatedAt: new Date('2024-10-10T13:45:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-09T11:10:00Z').toISOString(),
            patientId: 15,
            patientName: 'Patricia Phillips',
            changedBy: 'Admin Mary',
            fieldsChanged: ['email'],
            oldValue: { email: null },
            newValue: { email: 'patricia.phillips@yahoo.com' },
            reason: 'Email address added for communication',
            metadata: { ipAddress: '10.0.0.25', communicationPreference: 'email' },
            createdAt: new Date('2024-10-09T11:10:00Z').toISOString(),
            updatedAt: new Date('2024-10-09T11:10:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-08T15:25:00Z').toISOString(),
            patientId: 39,
            patientName: 'Jeremy Campbell',
            changedBy: 'Dr. Patel',
            fieldsChanged: ['medicalAidNumber'],
            oldValue: { medicalAidNumber: 'BP789012' },
            newValue: { medicalAidNumber: 'BP345678' },
            reason: 'Medical aid card replacement',
            metadata: { ipAddress: '172.16.0.10', cardReplacementReason: 'lost_card' },
            createdAt: new Date('2024-10-08T15:25:00Z').toISOString(),
            updatedAt: new Date('2024-10-08T15:25:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-07T08:50:00Z').toISOString(),
            patientId: 27,
            patientName: 'Cynthia Parker',
            changedBy: 'System Update',
            fieldsChanged: ['updatedAt'],
            oldValue: { updatedAt: '2024-08-15T14:20:00Z' },
            newValue: { updatedAt: '2024-10-07T08:50:00Z' },
            reason: null,
            metadata: { automated: true, trigger: 'system_maintenance' },
            createdAt: new Date('2024-10-07T08:50:00Z').toISOString(),
            updatedAt: new Date('2024-10-07T08:50:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-06T12:35:00Z').toISOString(),
            patientId: 50,
            patientName: 'Wayne Evans',
            changedBy: 'Nurse Johnson',
            fieldsChanged: ['active'],
            oldValue: { active: false },
            newValue: { active: true },
            reason: 'Patient returned for treatment',
            metadata: { ipAddress: '192.168.1.102', returnDate: '2024-10-06' },
            createdAt: new Date('2024-10-06T12:35:00Z').toISOString(),
            updatedAt: new Date('2024-10-06T12:35:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-05T16:00:00Z').toISOString(),
            patientId: 18,
            patientName: 'Alice Edwards',
            changedBy: 'Reception Desk',
            fieldsChanged: ['address', 'postalCode'],
            oldValue: { address: '852 River Road', postalCode: '4001' },
            newValue: { address: '963 Mountain View', postalCode: '7700' },
            reason: 'Address change notification',
            metadata: null,
            createdAt: new Date('2024-10-05T16:00:00Z').toISOString(),
            updatedAt: new Date('2024-10-05T16:00:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-04T10:20:00Z').toISOString(),
            patientId: 42,
            patientName: 'Ralph Collins',
            changedBy: 'Dr. Smith',
            fieldsChanged: ['idType', 'saIdNumber', 'passportNumber'],
            oldValue: { idType: 'passport', saIdNumber: null, passportNumber: 'IE456789123' },
            newValue: { idType: 'sa_id', saIdNumber: '7809185432100', passportNumber: null },
            reason: 'Document type change - obtained SA ID',
            metadata: { ipAddress: '192.168.1.101', documentDate: '2024-09-30' },
            createdAt: new Date('2024-10-04T10:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-04T10:20:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-03T14:55:00Z').toISOString(),
            patientId: 31,
            patientName: 'Joyce Stewart',
            changedBy: 'Admin Mary',
            fieldsChanged: ['lastName'],
            oldValue: { lastName: 'Stuart' },
            newValue: { lastName: 'Stewart' },
            reason: 'Surname spelling correction',
            metadata: { ipAddress: '10.0.0.25', correctionSource: 'official_document' },
            createdAt: new Date('2024-10-03T14:55:00Z').toISOString(),
            updatedAt: new Date('2024-10-03T14:55:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-02T09:40:00Z').toISOString(),
            patientId: 55,
            patientName: 'Eugene Morris',
            changedBy: 'Nurse Johnson',
            fieldsChanged: ['emergencyContactPhone'],
            oldValue: { emergencyContactPhone: '+27 82 666 7777' },
            newValue: { emergencyContactPhone: '+27 83 888 9999' },
            reason: 'Emergency contact updated their number',
            metadata: { ipAddress: '192.168.1.102', contactConfirmed: true },
            createdAt: new Date('2024-10-02T09:40:00Z').toISOString(),
            updatedAt: new Date('2024-10-02T09:40:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-10-01T13:15:00Z').toISOString(),
            patientId: 4,
            patientName: 'Harold Rogers',
            changedBy: 'Dr. Patel',
            fieldsChanged: ['medicalAid'],
            oldValue: { medicalAid: 'Sizani Medical Aid' },
            newValue: { medicalAid: 'Keyhealth Medical Scheme' },
            reason: 'Medical aid provider changed',
            metadata: { ipAddress: '172.16.0.10', effectiveDate: '2024-10-01' },
            createdAt: new Date('2024-10-01T13:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-01T13:15:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-09-30T11:30:00Z').toISOString(),
            patientId: 48,
            patientName: 'Brenda Cook',
            changedBy: 'System Update',
            fieldsChanged: ['active'],
            oldValue: { active: true },
            newValue: { active: false },
            reason: null,
            metadata: { automated: true, trigger: 'quarterly_cleanup', inactivityPeriod: '6_months' },
            createdAt: new Date('2024-09-30T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-30T11:30:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-09-29T15:45:00Z').toISOString(),
            patientId: 23,
            patientName: 'Russell Bailey',
            changedBy: 'Reception Desk',
            fieldsChanged: ['phone', 'city'],
            oldValue: { phone: '+27 84 333 4444', city: 'Bloemfontein' },
            newValue: { phone: '+27 85 555 6666', city: 'Cape Town' },
            reason: 'Patient moved and updated contact info',
            metadata: { ipAddress: '192.168.1.50', updateDate: '2024-09-29' },
            createdAt: new Date('2024-09-29T15:45:00Z').toISOString(),
            updatedAt: new Date('2024-09-29T15:45:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-09-28T08:25:00Z').toISOString(),
            patientId: 36,
            patientName: 'Jean Rivera',
            changedBy: 'Dr. Smith',
            fieldsChanged: ['email'],
            oldValue: { email: 'j.rivera@oldmail.com' },
            newValue: { email: 'jean.rivera@newmail.com' },
            reason: 'Email address change requested',
            metadata: { ipAddress: '192.168.1.101', emailVerificationSent: true },
            createdAt: new Date('2024-09-28T08:25:00Z').toISOString(),
            updatedAt: new Date('2024-09-28T08:25:00Z').toISOString(),
        },
        {
            timestamp: new Date('2024-09-27T12:10:00Z').toISOString(),
            patientId: 57,
            patientName: 'Martha Cooper',
            changedBy: 'Admin Mary',
            fieldsChanged: ['passportNumber', 'passportCountry'],
            oldValue: { passportNumber: 'NZ987654321', passportCountry: 'New Zealand' },
            newValue: { passportNumber: 'NZ123456789', passportCountry: 'New Zealand' },
            reason: 'Passport number correction after verification',
            metadata: { ipAddress: '10.0.0.25', verificationCompleted: true },
            createdAt: new Date('2024-09-27T12:10:00Z').toISOString(),
            updatedAt: new Date('2024-09-27T12:10:00Z').toISOString(),
        }
    ];

    await db.insert(auditLogs).values(sampleAuditLogs);
    
    console.log('✅ Audit logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});