import { db } from '@/db';
import { bills } from '@/db/schema';

async function main() {
    const sampleBills = [
        {
            patientId: 1,
            billDate: new Date('2024-07-15').toISOString(),
            amount: 25.00,
            description: 'Office Visit Copay',
            status: 'paid',
            dueDate: new Date('2024-08-14').toISOString(),
            createdAt: new Date('2024-07-15').toISOString(),
        },
        {
            patientId: 2,
            billDate: new Date('2024-08-03').toISOString(),
            amount: 185.50,
            description: 'Annual Physical Exam',
            status: 'pending',
            dueDate: new Date('2024-09-02').toISOString(),
            createdAt: new Date('2024-08-03').toISOString(),
        },
        {
            patientId: 3,
            billDate: new Date('2024-06-20').toISOString(),
            amount: 125.75,
            description: 'Blood Work Panel',
            status: 'overdue',
            dueDate: new Date('2024-07-20').toISOString(),
            createdAt: new Date('2024-06-20').toISOString(),
        },
        {
            patientId: 1,
            billDate: new Date('2024-09-10').toISOString(),
            amount: 320.00,
            description: 'X-Ray Imaging',
            status: 'paid',
            dueDate: new Date('2024-10-10').toISOString(),
            createdAt: new Date('2024-09-10').toISOString(),
        },
        {
            patientId: 4,
            billDate: new Date('2024-08-18').toISOString(),
            amount: 275.25,
            description: 'Specialist Consultation',
            status: 'pending',
            dueDate: new Date('2024-09-17').toISOString(),
            createdAt: new Date('2024-08-18').toISOString(),
        },
        {
            patientId: 5,
            billDate: new Date('2024-07-05').toISOString(),
            amount: 45.00,
            description: 'Vaccination Administration',
            status: 'paid',
            dueDate: new Date('2024-08-04').toISOString(),
            createdAt: new Date('2024-07-05').toISOString(),
        },
        {
            patientId: 2,
            billDate: new Date('2024-06-12').toISOString(),
            amount: 35.50,
            description: 'Prescription Refill',
            status: 'overdue',
            dueDate: new Date('2024-07-12').toISOString(),
            createdAt: new Date('2024-06-12').toISOString(),
        },
        {
            patientId: 6,
            billDate: new Date('2024-09-25').toISOString(),
            amount: 150.00,
            description: 'Follow-up Visit',
            status: 'pending',
            dueDate: new Date('2024-10-25').toISOString(),
            createdAt: new Date('2024-09-25').toISOString(),
        },
        {
            patientId: 7,
            billDate: new Date('2024-08-30').toISOString(),
            amount: 850.75,
            description: 'MRI Imaging',
            status: 'paid',
            dueDate: new Date('2024-09-29').toISOString(),
            createdAt: new Date('2024-08-30').toISOString(),
        },
        {
            patientId: 3,
            billDate: new Date('2024-09-15').toISOString(),
            amount: 95.25,
            description: 'Blood Work Panel',
            status: 'pending',
            dueDate: new Date('2024-10-15').toISOString(),
            createdAt: new Date('2024-09-15').toISOString(),
        },
        {
            patientId: 8,
            billDate: new Date('2024-07-22').toISOString(),
            amount: 1250.00,
            description: 'Minor Surgical Procedure',
            status: 'paid',
            dueDate: new Date('2024-08-21').toISOString(),
            createdAt: new Date('2024-07-22').toISOString(),
        },
        {
            patientId: 4,
            billDate: new Date('2024-06-08').toISOString(),
            amount: 50.00,
            description: 'Office Visit Copay',
            status: 'overdue',
            dueDate: new Date('2024-07-08').toISOString(),
            createdAt: new Date('2024-06-08').toISOString(),
        },
        {
            patientId: 9,
            billDate: new Date('2024-08-14').toISOString(),
            amount: 425.50,
            description: 'CT Scan Imaging',
            status: 'pending',
            dueDate: new Date('2024-09-13').toISOString(),
            createdAt: new Date('2024-08-14').toISOString(),
        },
        {
            patientId: 10,
            billDate: new Date('2024-09-08').toISOString(),
            amount: 220.00,
            description: 'Annual Physical Exam',
            status: 'paid',
            dueDate: new Date('2024-10-08').toISOString(),
            createdAt: new Date('2024-09-08').toISOString(),
        },
        {
            patientId: 5,
            billDate: new Date('2024-07-18').toISOString(),
            amount: 75.75,
            description: 'Vaccination Administration',
            status: 'paid',
            dueDate: new Date('2024-08-17').toISOString(),
            createdAt: new Date('2024-07-18').toISOString(),
        },
        {
            patientId: 1,
            billDate: new Date('2024-06-25').toISOString(),
            amount: 180.25,
            description: 'Follow-up Visit',
            status: 'overdue',
            dueDate: new Date('2024-07-25').toISOString(),
            createdAt: new Date('2024-06-25').toISOString(),
        },
        {
            patientId: 11,
            billDate: new Date('2024-08-28').toISOString(),
            amount: 65.00,
            description: 'Prescription Refill',
            status: 'pending',
            dueDate: new Date('2024-09-27').toISOString(),
            createdAt: new Date('2024-08-28').toISOString(),
        },
        {
            patientId: 6,
            billDate: new Date('2024-09-20').toISOString(),
            amount: 295.50,
            description: 'Specialist Consultation',
            status: 'paid',
            dueDate: new Date('2024-10-20').toISOString(),
            createdAt: new Date('2024-09-20').toISOString(),
        },
        {
            patientId: 12,
            billDate: new Date('2024-07-11').toISOString(),
            amount: 110.25,
            description: 'Blood Work Panel',
            status: 'paid',
            dueDate: new Date('2024-08-10').toISOString(),
            createdAt: new Date('2024-07-11').toISOString(),
        },
        {
            patientId: 8,
            billDate: new Date('2024-06-30').toISOString(),
            amount: 40.00,
            description: 'Office Visit Copay',
            status: 'overdue',
            dueDate: new Date('2024-07-30').toISOString(),
            createdAt: new Date('2024-06-30').toISOString(),
        },
        {
            patientId: 13,
            billDate: new Date('2024-08-22').toISOString(),
            amount: 760.00,
            description: 'Ultrasound Imaging',
            status: 'pending',
            dueDate: new Date('2024-09-21').toISOString(),
            createdAt: new Date('2024-08-22').toISOString(),
        },
        {
            patientId: 14,
            billDate: new Date('2024-09-12').toISOString(),
            amount: 195.75,
            description: 'Annual Physical Exam',
            status: 'paid',
            dueDate: new Date('2024-10-12').toISOString(),
            createdAt: new Date('2024-09-12').toISOString(),
        },
        {
            patientId: 7,
            billDate: new Date('2024-07-08').toISOString(),
            amount: 55.50,
            description: 'Vaccination Administration',
            status: 'paid',
            dueDate: new Date('2024-08-07').toISOString(),
            createdAt: new Date('2024-07-08').toISOString(),
        },
        {
            patientId: 15,
            billDate: new Date('2024-06-18').toISOString(),
            amount: 1150.25,
            description: 'Endoscopy Procedure',
            status: 'overdue',
            dueDate: new Date('2024-07-18').toISOString(),
            createdAt: new Date('2024-06-18').toISOString(),
        },
        {
            patientId: 9,
            billDate: new Date('2024-09-05').toISOString(),
            amount: 85.00,
            description: 'Blood Work Panel',
            status: 'pending',
            dueDate: new Date('2024-10-05').toISOString(),
            createdAt: new Date('2024-09-05').toISOString(),
        },
        {
            patientId: 10,
            billDate: new Date('2024-08-07').toISOString(),
            amount: 250.75,
            description: 'X-Ray Imaging',
            status: 'paid',
            dueDate: new Date('2024-09-06').toISOString(),
            createdAt: new Date('2024-08-07').toISOString(),
        },
        {
            patientId: 3,
            billDate: new Date('2024-07-28').toISOString(),
            amount: 30.00,
            description: 'Office Visit Copay',
            status: 'paid',
            dueDate: new Date('2024-08-27').toISOString(),
            createdAt: new Date('2024-07-28').toISOString(),
        },
        {
            patientId: 16,
            billDate: new Date('2024-06-15').toISOString(),
            amount: 345.50,
            description: 'Specialist Consultation',
            status: 'overdue',
            dueDate: new Date('2024-07-15').toISOString(),
            createdAt: new Date('2024-06-15').toISOString(),
        },
        {
            patientId: 11,
            billDate: new Date('2024-09-18').toISOString(),
            amount: 125.25,
            description: 'Follow-up Visit',
            status: 'pending',
            dueDate: new Date('2024-10-18').toISOString(),
            createdAt: new Date('2024-09-18').toISOString(),
        },
        {
            patientId: 4,
            billDate: new Date('2024-08-11').toISOString(),
            amount: 45.75,
            description: 'Prescription Refill',
            status: 'paid',
            dueDate: new Date('2024-09-10').toISOString(),
            createdAt: new Date('2024-08-11').toISOString(),
        },
        {
            patientId: 17,
            billDate: new Date('2024-07-03').toISOString(),
            amount: 675.00,
            description: 'Cardiac Stress Test',
            status: 'paid',
            dueDate: new Date('2024-08-02').toISOString(),
            createdAt: new Date('2024-07-03').toISOString(),
        },
        {
            patientId: 12,
            billDate: new Date('2024-09-22').toISOString(),
            amount: 155.50,
            description: 'Annual Physical Exam',
            status: 'pending',
            dueDate: new Date('2024-10-22').toISOString(),
            createdAt: new Date('2024-09-22').toISOString(),
        },
        {
            patientId: 5,
            billDate: new Date('2024-06-28').toISOString(),
            amount: 225.75,
            description: 'X-Ray Imaging',
            status: 'overdue',
            dueDate: new Date('2024-07-28').toISOString(),
            createdAt: new Date('2024-06-28').toISOString(),
        },
        {
            patientId: 18,
            billDate: new Date('2024-08-25').toISOString(),
            amount: 95.00,
            description: 'Blood Work Panel',
            status: 'pending',
            dueDate: new Date('2024-09-24').toISOString(),
            createdAt: new Date('2024-08-25').toISOString(),
        },
        {
            patientId: 6,
            billDate: new Date('2024-07-16').toISOString(),
            amount: 35.00,
            description: 'Office Visit Copay',
            status: 'paid',
            dueDate: new Date('2024-08-15').toISOString(),
            createdAt: new Date('2024-07-16').toISOString(),
        },
    ];

    await db.insert(bills).values(sampleBills);
    
    console.log('✅ Bills seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});