import { db } from '@/db';
import { clinicPatients } from '@/db/schema';

async function main() {
    const samplePatients = [
        {
            firstName: 'Emma',
            lastName: 'Johnson',
            email: 'emma.johnson@gmail.com',
            phone: '(555) 123-4567',
            dateOfBirth: '1992-03-15',
            address: '1425 Oak Street, Springfield, IL 62701',
            emergencyContact: 'Michael Johnson (Spouse) - (555) 123-4568',
            insuranceInfo: JSON.stringify({
                provider: 'Blue Cross Blue Shield',
                policyNumber: 'BC12345678',
                groupNumber: 'GRP001'
            }),
            registrationDate: '2024-01-15',
            status: 'active',
            active: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            firstName: 'James',
            lastName: 'Wilson',
            email: 'james.wilson@yahoo.com',
            phone: '555-234-5678',
            dateOfBirth: '1985-07-22',
            address: '892 Pine Avenue, Riverside, CA 92501',
            emergencyContact: 'Sarah Wilson (Wife) - (555) 234-5679',
            insuranceInfo: JSON.stringify({
                provider: 'Aetna',
                policyNumber: 'AET987654321',
                groupNumber: 'GRP445'
            }),
            registrationDate: '2024-02-03',
            status: 'active',
            active: true,
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            firstName: 'Sophia',
            lastName: 'Martinez',
            email: 'sophia.martinez@outlook.com',
            phone: '(555) 345-6789',
            dateOfBirth: '2010-11-08',
            address: '456 Elm Drive, Austin, TX 73301',
            emergencyContact: 'Carlos Martinez (Father) - (555) 345-6790',
            insuranceInfo: JSON.stringify({
                provider: 'UnitedHealth',
                policyNumber: 'UH456789012',
                groupNumber: 'GRP789'
            }),
            registrationDate: '2024-02-18',
            status: 'active',
            active: true,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            firstName: 'Robert',
            lastName: 'Chen',
            email: 'robert.chen@gmail.com',
            phone: '555.456.7890',
            dateOfBirth: '1958-12-03',
            address: '2103 Maple Street, Portland, OR 97201',
            emergencyContact: 'Linda Chen (Wife) - (555) 456-7891',
            insuranceInfo: JSON.stringify({
                provider: 'Medicare',
                policyNumber: 'MED123456789',
                groupNumber: 'MED001'
            }),
            registrationDate: '2024-03-05',
            status: 'active',
            active: true,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            firstName: 'Isabella',
            lastName: 'Thompson',
            email: 'isabella.thompson@hotmail.com',
            phone: '(555) 567-8901',
            dateOfBirth: '1995-04-12',
            address: '789 Cedar Lane, Denver, CO 80202',
            emergencyContact: 'David Thompson (Brother) - (555) 567-8902',
            insuranceInfo: JSON.stringify({
                provider: 'Kaiser Permanente',
                policyNumber: 'KP789012345',
                groupNumber: 'KP334'
            }),
            registrationDate: '2024-03-20',
            status: 'active',
            active: true,
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        {
            firstName: 'William',
            lastName: 'Davis',
            email: 'william.davis@gmail.com',
            phone: '555-678-9012',
            dateOfBirth: '1979-09-28',
            address: '1567 Birch Boulevard, Miami, FL 33101',
            emergencyContact: 'Jennifer Davis (Wife) - (555) 678-9013',
            insuranceInfo: JSON.stringify({
                provider: 'Cigna',
                policyNumber: 'CIG345678901',
                groupNumber: 'CIG556'
            }),
            registrationDate: '2024-04-02',
            status: 'active',
            active: true,
            createdAt: new Date('2024-04-02').toISOString(),
            updatedAt: new Date('2024-04-02').toISOString(),
        },
        {
            firstName: 'Ava',
            lastName: 'Rodriguez',
            email: 'ava.rodriguez@yahoo.com',
            phone: '(555) 789-0123',
            dateOfBirth: '2015-06-14',
            address: '234 Willow Way, Seattle, WA 98101',
            emergencyContact: 'Maria Rodriguez (Mother) - (555) 789-0124',
            insuranceInfo: JSON.stringify({
                provider: 'Medicaid',
                policyNumber: 'MCD567890123',
                groupNumber: 'MCD223'
            }),
            registrationDate: '2024-04-15',
            status: 'active',
            active: true,
            createdAt: new Date('2024-04-15').toISOString(),
            updatedAt: new Date('2024-04-15').toISOString(),
        },
        {
            firstName: 'Michael',
            lastName: 'Brown',
            email: 'michael.brown@outlook.com',
            phone: '555.890.1234',
            dateOfBirth: '1963-01-19',
            address: '890 Poplar Place, Phoenix, AZ 85001',
            emergencyContact: 'Susan Brown (Daughter) - (555) 890-1235',
            insuranceInfo: JSON.stringify({
                provider: 'Blue Cross Blue Shield',
                policyNumber: 'BC890123456',
                groupNumber: 'GRP778'
            }),
            registrationDate: '2024-05-01',
            status: 'active',
            active: true,
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-05-01').toISOString(),
        },
        {
            firstName: 'Olivia',
            lastName: 'Garcia',
            email: 'olivia.garcia@gmail.com',
            phone: '(555) 901-2345',
            dateOfBirth: '1988-08-07',
            address: '345 Spruce Street, Nashville, TN 37201',
            emergencyContact: 'Antonio Garcia (Husband) - (555) 901-2346',
            insuranceInfo: JSON.stringify({
                provider: 'Aetna',
                policyNumber: 'AET123456789',
                groupNumber: 'GRP889'
            }),
            registrationDate: '2024-05-18',
            status: 'active',
            active: true,
            createdAt: new Date('2024-05-18').toISOString(),
            updatedAt: new Date('2024-05-18').toISOString(),
        },
        {
            firstName: 'Ethan',
            lastName: 'Miller',
            email: 'ethan.miller@hotmail.com',
            phone: '555-012-3456',
            dateOfBirth: '2008-02-25',
            address: '678 Ash Avenue, Boston, MA 02101',
            emergencyContact: 'Karen Miller (Mother) - (555) 012-3457',
            insuranceInfo: JSON.stringify({
                provider: 'UnitedHealth',
                policyNumber: 'UH234567890',
                groupNumber: 'UH445'
            }),
            registrationDate: '2024-06-03',
            status: 'active',
            active: true,
            createdAt: new Date('2024-06-03').toISOString(),
            updatedAt: new Date('2024-06-03').toISOString(),
        },
        {
            firstName: 'Charlotte',
            lastName: 'Anderson',
            email: 'charlotte.anderson@yahoo.com',
            phone: '(555) 123-4567',
            dateOfBirth: '1991-10-11',
            address: '1234 Hickory Hill, Atlanta, GA 30301',
            emergencyContact: 'Ryan Anderson (Boyfriend) - (555) 123-4568',
            insuranceInfo: JSON.stringify({
                provider: 'Kaiser Permanente',
                policyNumber: 'KP567890123',
                groupNumber: 'KP667'
            }),
            registrationDate: '2024-06-20',
            status: 'active',
            active: true,
            createdAt: new Date('2024-06-20').toISOString(),
            updatedAt: new Date('2024-06-20').toISOString(),
        },
        {
            firstName: 'Benjamin',
            lastName: 'Taylor',
            email: 'benjamin.taylor@gmail.com',
            phone: '555.234.5678',
            dateOfBirth: '1956-05-30',
            address: '567 Magnolia Drive, Charlotte, NC 28201',
            emergencyContact: 'Patricia Taylor (Wife) - (555) 234-5679',
            insuranceInfo: JSON.stringify({
                provider: 'Medicare',
                policyNumber: 'MED789012345',
                groupNumber: 'MED002'
            }),
            registrationDate: '2024-07-05',
            status: 'active',
            active: true,
            createdAt: new Date('2024-07-05').toISOString(),
            updatedAt: new Date('2024-07-05').toISOString(),
        },
        {
            firstName: 'Amelia',
            lastName: 'Thomas',
            email: 'amelia.thomas@outlook.com',
            phone: '(555) 345-6789',
            dateOfBirth: '2012-12-09',
            address: '912 Dogwood Court, Dallas, TX 75201',
            emergencyContact: 'Steven Thomas (Father) - (555) 345-6790',
            insuranceInfo: JSON.stringify({
                provider: 'Cigna',
                policyNumber: 'CIG890123456',
                groupNumber: 'CIG778'
            }),
            registrationDate: '2024-07-22',
            status: 'active',
            active: true,
            createdAt: new Date('2024-07-22').toISOString(),
            updatedAt: new Date('2024-07-22').toISOString(),
        },
        {
            firstName: 'Alexander',
            lastName: 'Jackson',
            email: 'alexander.jackson@hotmail.com',
            phone: '555-456-7890',
            dateOfBirth: '1983-03-17',
            address: '1678 Sycamore Lane, San Diego, CA 92101',
            emergencyContact: 'Michelle Jackson (Wife) - (555) 456-7891',
            insuranceInfo: JSON.stringify({
                provider: 'Blue Cross Blue Shield',
                policyNumber: 'BC456789012',
                groupNumber: 'GRP990'
            }),
            registrationDate: '2024-08-08',
            status: 'active',
            active: true,
            createdAt: new Date('2024-08-08').toISOString(),
            updatedAt: new Date('2024-08-08').toISOString(),
        },
        {
            firstName: 'Mia',
            lastName: 'White',
            email: 'mia.white@gmail.com',
            phone: '(555) 567-8901',
            dateOfBirth: '1996-11-23',
            address: '2345 Redwood Road, Las Vegas, NV 89101',
            emergencyContact: 'Jessica White (Sister) - (555) 567-8902',
            insuranceInfo: JSON.stringify({
                provider: 'Aetna',
                policyNumber: 'AET678901234',
                groupNumber: 'GRP112'
            }),
            registrationDate: '2024-08-25',
            status: 'active',
            active: true,
            createdAt: new Date('2024-08-25').toISOString(),
            updatedAt: new Date('2024-08-25').toISOString(),
        },
        {
            firstName: 'Daniel',
            lastName: 'Harris',
            email: 'daniel.harris@yahoo.com',
            phone: '555.678.9012',
            dateOfBirth: '1960-07-06',
            address: '789 Chestnut Street, Philadelphia, PA 19101',
            emergencyContact: 'Margaret Harris (Wife) - (555) 678-9013',
            insuranceInfo: JSON.stringify({
                provider: 'Medicare',
                policyNumber: 'MED345678901',
                groupNumber: 'MED003'
            }),
            registrationDate: '2024-09-10',
            status: 'active',
            active: true,
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-09-10').toISOString(),
        },
        {
            firstName: 'Harper',
            lastName: 'Martin',
            email: 'harper.martin@outlook.com',
            phone: '(555) 789-0123',
            dateOfBirth: '2014-04-02',
            address: '456 Walnut Way, Minneapolis, MN 55401',
            emergencyContact: 'Andrew Martin (Father) - (555) 789-0124',
            insuranceInfo: JSON.stringify({
                provider: 'UnitedHealth',
                policyNumber: 'UH890123456',
                groupNumber: 'UH223'
            }),
            registrationDate: '2024-09-28',
            status: 'active',
            active: true,
            createdAt: new Date('2024-09-28').toISOString(),
            updatedAt: new Date('2024-09-28').toISOString(),
        },
        {
            firstName: 'Logan',
            lastName: 'Clark',
            email: 'logan.clark@hotmail.com',
            phone: '555-890-1234',
            dateOfBirth: '1987-01-14',
            address: '1023 Pecan Place, Houston, TX 77001',
            emergencyContact: 'Ashley Clark (Wife) - (555) 890-1235',
            insuranceInfo: JSON.stringify({
                provider: 'Kaiser Permanente',
                policyNumber: 'KP123456789',
                groupNumber: 'KP334'
            }),
            registrationDate: '2024-10-15',
            status: 'active',
            active: true,
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
            firstName: 'Evelyn',
            lastName: 'Lewis',
            email: 'evelyn.lewis@gmail.com',
            phone: '(555) 901-2345',
            dateOfBirth: '2007-09-20',
            address: '1567 Pine Ridge Drive, San Antonio, TX 78201',
            emergencyContact: 'Robert Lewis (Father) - (555) 901-2346',
            insuranceInfo: JSON.stringify({
                provider: 'Medicaid',
                policyNumber: 'MCD234567890',
                groupNumber: 'MCD445'
            }),
            registrationDate: '2024-11-02',
            status: 'active',
            active: true,
            createdAt: new Date('2024-11-02').toISOString(),
            updatedAt: new Date('2024-11-02').toISOString(),
        },
        {
            firstName: 'Lucas',
            lastName: 'Walker',
            email: 'lucas.walker@yahoo.com',
            phone: '555.012.3456',
            dateOfBirth: '1975-06-18',
            address: '890 Oak Hill Road, Detroit, MI 48201',
            emergencyContact: 'Nicole Walker (Wife) - (555) 012-3457',
            insuranceInfo: JSON.stringify({
                provider: 'Cigna',
                policyNumber: 'CIG567890123',
                groupNumber: 'CIG889'
            }),
            registrationDate: '2024-11-20',
            status: 'active',
            active: true,
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            firstName: 'Grace',
            lastName: 'Hall',
            email: 'grace.hall@outlook.com',
            phone: '(555) 123-4567',
            dateOfBirth: '1993-12-31',
            address: '234 Maple Ridge Lane, Orlando, FL 32801',
            emergencyContact: 'Emily Hall (Mother) - (555) 123-4568',
            insuranceInfo: JSON.stringify({
                provider: 'Blue Cross Blue Shield',
                policyNumber: 'BC234567890',
                groupNumber: 'GRP445'
            }),
            registrationDate: '2024-12-05',
            status: 'active',
            active: true,
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            firstName: 'Samuel',
            lastName: 'Allen',
            email: 'samuel.allen@hotmail.com',
            phone: '555-234-5678',
            dateOfBirth: '1952-02-10',
            address: '567 Cedar Heights Circle, Salt Lake City, UT 84101',
            emergencyContact: 'Dorothy Allen (Wife) - (555) 234-5679',
            insuranceInfo: JSON.stringify({
                provider: 'Medicare',
                policyNumber: 'MED901234567',
                groupNumber: 'MED004'
            }),
            registrationDate: '2024-12-18',
            status: 'active',
            active: true,
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            firstName: 'Lillian',
            lastName: 'Young',
            email: 'lillian.young@gmail.com',
            phone: '(555) 345-6789',
            dateOfBirth: '2009-08-26',
            address: '912 Elm Grove Street, Kansas City, MO 64101',
            emergencyContact: 'Brian Young (Father) - (555) 345-6790',
            insuranceInfo: JSON.stringify({
                provider: 'Aetna',
                policyNumber: 'AET456789012',
                groupNumber: 'GRP667'
            }),
            registrationDate: '2024-01-28',
            status: 'inactive',
            active: false,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            firstName: 'Owen',
            lastName: 'King',
            email: 'owen.king@yahoo.com',
            phone: '555.456.7890',
            dateOfBirth: '1989-05-13',
            address: '1345 Birch Valley Drive, Tampa, FL 33601',
            emergencyContact: 'Samantha King (Wife) - (555) 456-7891',
            insuranceInfo: JSON.stringify({
                provider: 'UnitedHealth',
                policyNumber: 'UH678901234',
                groupNumber: 'UH556'
            }),
            registrationDate: '2024-02-12',
            status: 'inactive',
            active: false,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-09-20').toISOString(),
        },
        {
            firstName: 'Zoe',
            lastName: 'Wright',
            email: 'zoe.wright@outlook.com',
            phone: '(555) 567-8901',
            dateOfBirth: '2013-03-05',
            address: '678 Willow Creek Road, Cleveland, OH 44101',
            emergencyContact: 'Jason Wright (Father) - (555) 567-8902',
            insuranceInfo: JSON.stringify({
                provider: 'Kaiser Permanente',
                policyNumber: 'KP345678901',
                groupNumber: 'KP778'
            }),
            registrationDate: '2024-03-08',
            status: 'inactive',
            active: false,
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-10-12').toISOString(),
        },
        {
            firstName: 'Gabriel',
            lastName: 'Lopez',
            email: 'gabriel.lopez@hotmail.com',
            phone: '555-678-9012',
            dateOfBirth: '1964-11-17',
            address: '1890 Spruce Mountain Lane, Tucson, AZ 85701',
            emergencyContact: 'Maria Lopez (Daughter) - (555) 678-9013',
            insuranceInfo: JSON.stringify({
                provider: 'Medicare',
                policyNumber: 'MED567890123',
                groupNumber: 'MED005'
            }),
            registrationDate: '2024-04-22',
            status: 'inactive',
            active: false,
            createdAt: new Date('2024-04-22').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            firstName: 'Scarlett',
            lastName: 'Hill',
            email: 'scarlett.hill@gmail.com',
            phone: '(555) 789-0123',
            dateOfBirth: '1998-07-04',
            address: '234 Poplar Ridge Avenue, Raleigh, NC 27601',
            emergencyContact: 'Madison Hill (Sister) - (555) 789-0124',
            insuranceInfo: JSON.stringify({
                provider: 'Cigna',
                policyNumber: 'CIG234567890',
                groupNumber: 'CIG445'
            }),
            registrationDate: '2024-05-30',
            status: 'inactive',
            active: false,
            createdAt: new Date('2024-05-30').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            firstName: 'Carter',
            lastName: 'Green',
            email: 'carter.green@yahoo.com',
            phone: '555.890.1234',
            dateOfBirth: '2006-01-29',
            address: '567 Hickory Point Drive, Memphis, TN 38101',
            emergencyContact: 'Rachel Green (Mother) - (555) 890-1235',
            insuranceInfo: JSON.stringify({
                provider: 'Blue Cross Blue Shield',
                policyNumber: 'BC789012345',
                groupNumber: 'GRP223'
            }),
            registrationDate: '2024-07-14',
            status: 'archived',
            active: false,
            createdAt: new Date('2024-07-14').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            firstName: 'Luna',
            lastName: 'Adams',
            email: 'luna.adams@outlook.com',
            phone: '(555) 901-2345',
            dateOfBirth: '1981-10-07',
            address: '890 Ash Creek Boulevard, Louisville, KY 40201',
            emergencyContact: 'Tyler Adams (Husband) - (555) 901-2346',
            insuranceInfo: JSON.stringify({
                provider: 'Aetna',
                policyNumber: 'AET890123456',
                groupNumber: 'GRP334'
            }),
            registrationDate: '2024-08-18',
            status: 'archived',
            active: false,
            createdAt: new Date('2024-08-18').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        }
    ];

    await db.insert(clinicPatients).values(samplePatients);
    
    console.log('✅ Clinic patients seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});