import { db } from '@/db';
import { medicalRecords } from '@/db/schema';

async function main() {
    const doctorNames = [
        'Dr. Sarah Johnson',
        'Dr. Michael Chen',
        'Dr. Emily Rodriguez',
        'Dr. David Kim',
        'Dr. Jennifer Walsh',
        'Dr. Robert Thompson',
        'Dr. Lisa Patel',
        'Dr. James Wilson'
    ];

    const sampleMedicalRecords = [
        // Lab Results (40% - 24 records)
        {
            patientId: 1,
            recordDate: new Date('2024-01-15').toISOString(),
            recordType: 'lab_result',
            title: 'Complete Blood Count',
            description: 'CBC with differential: WBC 7.2 K/uL (normal 4.5-11.0), RBC 4.8 M/uL (normal 4.5-5.5), Hemoglobin 14.2 g/dL (normal 13.5-17.5), Hematocrit 42.1% (normal 41-53), Platelets 285 K/uL (normal 150-450). All values within normal limits.',
            doctorName: 'Dr. Sarah Johnson',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            patientId: 2,
            recordDate: new Date('2024-02-03').toISOString(),
            recordType: 'lab_result',
            title: 'Lipid Panel',
            description: 'Fasting lipid profile: Total cholesterol 245 mg/dL (elevated, <200 desired), LDL 165 mg/dL (elevated, <100 optimal), HDL 38 mg/dL (low, >40 desired), Triglycerides 198 mg/dL (borderline high, <150 normal). Recommend dietary modifications and statin therapy.',
            doctorName: 'Dr. Michael Chen',
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            patientId: 3,
            recordDate: new Date('2024-03-12').toISOString(),
            recordType: 'lab_result',
            title: 'Thyroid Function Test',
            description: 'TSH 8.5 mIU/L (elevated, normal 0.4-4.0), Free T4 0.8 ng/dL (low normal 0.9-1.7), Free T3 2.8 pg/mL (normal 2.3-4.2). Results consistent with subclinical hypothyroidism. Recommend thyroid hormone replacement therapy.',
            doctorName: 'Dr. Emily Rodriguez',
            createdAt: new Date('2024-03-12').toISOString(),
        },
        {
            patientId: 4,
            recordDate: new Date('2024-04-08').toISOString(),
            recordType: 'lab_result',
            title: 'Hemoglobin A1C',
            description: 'HbA1c 8.2% (elevated, <7.0% target for diabetics, <5.7% normal). Indicates poor glycemic control over past 2-3 months. Recommend intensification of diabetes management with medication adjustment and lifestyle counseling.',
            doctorName: 'Dr. David Kim',
            createdAt: new Date('2024-04-08').toISOString(),
        },
        {
            patientId: 5,
            recordDate: new Date('2024-05-20').toISOString(),
            recordType: 'lab_result',
            title: 'Urinalysis',
            description: 'Specific gravity 1.020, pH 6.0, Protein negative, Glucose negative, Ketones negative, Blood negative, Leukocyte esterase negative, Nitrites negative, WBC 0-2/hpf, RBC 0-1/hpf, Bacteria few. Normal urinalysis with no evidence of infection or proteinuria.',
            doctorName: 'Dr. Jennifer Walsh',
            createdAt: new Date('2024-05-20').toISOString(),
        },
        {
            patientId: 6,
            recordDate: new Date('2024-06-14').toISOString(),
            recordType: 'lab_result',
            title: 'Complete Blood Count',
            description: 'CBC: WBC 12.8 K/uL (elevated, normal 4.5-11.0), RBC 4.2 M/uL (low normal), Hemoglobin 11.8 g/dL (low, normal 13.5-17.5), Platelets 185 K/uL (normal). Mild anemia and leukocytosis noted. Consider iron studies and infection workup.',
            doctorName: 'Dr. Robert Thompson',
            createdAt: new Date('2024-06-14').toISOString(),
        },
        {
            patientId: 7,
            recordDate: new Date('2024-07-02').toISOString(),
            recordType: 'lab_result',
            title: 'Lipid Panel',
            description: 'Total cholesterol 188 mg/dL (normal), LDL 110 mg/dL (above optimal), HDL 52 mg/dL (good), Triglycerides 95 mg/dL (normal). Overall good lipid profile with slightly elevated LDL. Continue current statin therapy.',
            doctorName: 'Dr. Lisa Patel',
            createdAt: new Date('2024-07-02').toISOString(),
        },
        {
            patientId: 8,
            recordDate: new Date('2024-08-16').toISOString(),
            recordType: 'lab_result',
            title: 'Thyroid Function Test',
            description: 'TSH 2.1 mIU/L (normal), Free T4 1.2 ng/dL (normal), Free T3 3.1 pg/mL (normal). Normal thyroid function on current levothyroxine dose. Continue current medication regimen.',
            doctorName: 'Dr. James Wilson',
            createdAt: new Date('2024-08-16').toISOString(),
        },
        {
            patientId: 1,
            recordDate: new Date('2024-09-05').toISOString(),
            recordType: 'lab_result',
            title: 'Hemoglobin A1C',
            description: 'HbA1c 6.8% (good control for diabetic, target <7.0%). Significant improvement from previous value of 8.2%. Patient showing excellent response to intensified diabetes management.',
            doctorName: 'Dr. Sarah Johnson',
            createdAt: new Date('2024-09-05').toISOString(),
        },
        {
            patientId: 2,
            recordDate: new Date('2024-10-12').toISOString(),
            recordType: 'lab_result',
            title: 'Urinalysis',
            description: 'Specific gravity 1.025, pH 5.5, Protein trace, Glucose negative, Ketones negative, Blood 1+, Leukocyte esterase positive, Nitrites positive, WBC 15-20/hpf, RBC 5-10/hpf, Bacteria many. Consistent with urinary tract infection. Urine culture pending.',
            doctorName: 'Dr. Michael Chen',
            createdAt: new Date('2024-10-12').toISOString(),
        },
        {
            patientId: 3,
            recordDate: new Date('2024-11-08').toISOString(),
            recordType: 'lab_result',
            title: 'Complete Blood Count',
            description: 'CBC: WBC 6.8 K/uL (normal), RBC 4.9 M/uL (normal), Hemoglobin 15.1 g/dL (normal), Hematocrit 44.2% (normal), Platelets 310 K/uL (normal). All parameters within normal limits.',
            doctorName: 'Dr. Emily Rodriguez',
            createdAt: new Date('2024-11-08').toISOString(),
        },
        {
            patientId: 4,
            recordDate: new Date('2024-12-01').toISOString(),
            recordType: 'lab_result',
            title: 'Lipid Panel',
            description: 'Total cholesterol 210 mg/dL (borderline high), LDL 135 mg/dL (borderline high), HDL 45 mg/dL (acceptable), Triglycerides 155 mg/dL (borderline high). Recommend dietary counseling and consider statin initiation.',
            doctorName: 'Dr. David Kim',
            createdAt: new Date('2024-12-01').toISOString(),
        },
        {
            patientId: 5,
            recordDate: new Date('2024-01-28').toISOString(),
            recordType: 'lab_result',
            title: 'Thyroid Function Test',
            description: 'TSH 0.2 mIU/L (low, normal 0.4-4.0), Free T4 2.1 ng/dL (elevated, normal 0.9-1.7). Suggests hyperthyroidism or overreplacement with thyroid hormone. Recommend dose reduction and repeat in 6 weeks.',
            doctorName: 'Dr. Jennifer Walsh',
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            patientId: 6,
            recordDate: new Date('2024-03-18').toISOString(),
            recordType: 'lab_result',
            title: 'Hemoglobin A1C',
            description: 'HbA1c 5.4% (normal, <5.7%). Excellent glycemic control. Patient has successfully maintained non-diabetic glucose levels through lifestyle modifications.',
            doctorName: 'Dr. Robert Thompson',
            createdAt: new Date('2024-03-18').toISOString(),
        },
        {
            patientId: 7,
            recordDate: new Date('2024-04-25').toISOString(),
            recordType: 'lab_result',
            title: 'Urinalysis',
            description: 'Normal urinalysis: Specific gravity 1.018, pH 6.5, all parameters negative, microscopy unremarkable. No evidence of infection, proteinuria, or hematuria.',
            doctorName: 'Dr. Lisa Patel',
            createdAt: new Date('2024-04-25').toISOString(),
        },
        {
            patientId: 8,
            recordDate: new Date('2024-06-30').toISOString(),
            recordType: 'lab_result',
            title: 'Complete Blood Count',
            description: 'CBC with mild abnormalities: WBC 4.2 K/uL (low normal), RBC 4.1 M/uL (low), Hemoglobin 12.8 g/dL (low normal), MCV 78 fL (low, normal 80-100). Findings suggest mild iron deficiency anemia. Iron studies recommended.',
            doctorName: 'Dr. James Wilson',
            createdAt: new Date('2024-06-30').toISOString(),
        },
        {
            patientId: 1,
            recordDate: new Date('2024-08-22').toISOString(),
            recordType: 'lab_result',
            title: 'Lipid Panel',
            description: 'Excellent lipid profile: Total cholesterol 165 mg/dL, LDL 88 mg/dL, HDL 58 mg/dL, Triglycerides 95 mg/dL. All values at target levels. Continue current statin and lifestyle modifications.',
            doctorName: 'Dr. Sarah Johnson',
            createdAt: new Date('2024-08-22').toISOString(),
        },
        {
            patientId: 2,
            recordDate: new Date('2024-10-18').toISOString(),
            recordType: 'lab_result',
            title: 'Thyroid Function Test',
            description: 'TSH 3.2 mIU/L (normal), Free T4 1.1 ng/dL (normal). Thyroid function stable on current levothyroxine dose. Continue current therapy with annual monitoring.',
            doctorName: 'Dr. Michael Chen',
            createdAt: new Date('2024-10-18').toISOString(),
        },
        {
            patientId: 3,
            recordDate: new Date('2024-11-25').toISOString(),
            recordType: 'lab_result',
            title: 'Hemoglobin A1C',
            description: 'HbA1c 7.8% (above target for diabetics). Represents slight worsening from previous 6.8%. Recommend medication adjustment and reinforcement of dietary compliance.',
            doctorName: 'Dr. Emily Rodriguez',
            createdAt: new Date('2024-11-25').toISOString(),
        },
        {
            patientId: 4,
            recordDate: new Date('2024-12-10').toISOString(),
            recordType: 'lab_result',
            title: 'Urinalysis',
            description: 'Urinalysis shows microalbuminuria: Protein 1+ (30 mg/dL), microscopic examination normal otherwise. Early sign of diabetic nephropathy. Recommend ACE inhibitor initiation and nephrology referral.',
            doctorName: 'Dr. David Kim',
            createdAt: new Date('2024-12-10').toISOString(),
        },
        {
            patientId: 5,
            recordDate: new Date('2024-02-14').toISOString(),
            recordType: 'lab_result',
            title: 'Complete Blood Count',
            description: 'Post-treatment CBC: WBC 8.5 K/uL (normal), RBC 4.6 M/uL (normal), Hemoglobin 13.8 g/dL (normal), Platelets 275 K/uL (normal). Complete resolution of previous anemia with iron supplementation.',
            doctorName: 'Dr. Jennifer Walsh',
            createdAt: new Date('2024-02-14').toISOString(),
        },
        {
            patientId: 6,
            recordDate: new Date('2024-05-08').toISOString(),
            recordType: 'lab_result',
            title: 'Lipid Panel',
            description: 'Pre-treatment baseline: Total cholesterol 268 mg/dL (high), LDL 185 mg/dL (very high), HDL 35 mg/dL (low), Triglycerides 240 mg/dL (high). Significant dyslipidemia requiring statin therapy and lifestyle intervention.',
            doctorName: 'Dr. Robert Thompson',
            createdAt: new Date('2024-05-08').toISOString(),
        },
        {
            patientId: 7,
            recordDate: new Date('2024-07-15').toISOString(),
            recordType: 'lab_result',
            title: 'Thyroid Function Test',
            description: 'Initial thyroid evaluation: TSH 15.2 mIU/L (markedly elevated), Free T4 0.6 ng/dL (low). Clear hypothyroidism requiring thyroid hormone replacement. Started on levothyroxine 50 mcg daily.',
            doctorName: 'Dr. Lisa Patel',
            createdAt: new Date('2024-07-15').toISOString(),
        },
        {
            patientId: 8,
            recordDate: new Date('2024-09-12').toISOString(),
            recordType: 'lab_result',
            title: 'Hemoglobin A1C',
            description: 'Initial diabetes screening: HbA1c 9.1% (diagnostic of diabetes, >6.5%). Patient requires immediate diabetes management including metformin initiation and diabetes education.',
            doctorName: 'Dr. James Wilson',
            createdAt: new Date('2024-09-12').toISOString(),
        },
        
        // Visit Notes (30% - 18 records)
        {
            patientId: 1,
            recordDate: new Date('2024-01-10').toISOString(),
            recordType: 'visit_note',
            title: 'Annual Physical Exam',
            description: 'Comprehensive annual physical examination. Patient reports feeling well with no new complaints. Vital signs: BP 128/82 mmHg, HR 72 bpm, Temp 98.6°F, BMI 26.8. Physical exam unremarkable except for mild hypertension. Discussed weight management, exercise routine, and medication compliance. Scheduled routine labs.',
            doctorName: 'Dr. Sarah Johnson',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            patientId: 2,
            recordDate: new Date('2024-02-20').toISOString(),
            recordType: 'visit_note',
            title: 'Hypertension Follow-up',
            description: 'Follow-up visit for hypertension management. Patient reports good medication compliance with lisinopril 10mg daily. Home BP readings averaging 135/85 mmHg. No side effects from medication. Physical exam shows no target organ damage. Increased lisinopril to 20mg daily and scheduled follow-up in 4 weeks.',
            doctorName: 'Dr. Michael Chen',
            createdAt: new Date('2024-02-20').toISOString(),
        },
        {
            patientId: 3,
            recordDate: new Date('2024-03-15').toISOString(),
            recordType: 'visit_note',
            title: 'Diabetes Management',
            description: 'Routine diabetes management visit. Patient reports improved dietary compliance and regular exercise. Blood glucose logs show fasting values 110-140 mg/dL. A1C pending. No symptoms of hypoglycemia or hyperglycemia. Feet examination normal, no neuropathy signs. Adjusted metformin dose and reinforced lifestyle modifications.',
            doctorName: 'Dr. Emily Rodriguez',
            createdAt: new Date('2024-03-15').toISOString(),
        },
        {
            patientId: 4,
            recordDate: new Date('2024-04-12').toISOString(),
            recordType: 'visit_note',
            title: 'Cold Symptoms',
            description: 'Patient presents with 3-day history of runny nose, mild sore throat, and low-grade fever. No cough, chest pain, or shortness of breath. Physical exam shows mild nasal congestion, erythematous throat without exudate. Lungs clear. Diagnosed with viral upper respiratory infection. Recommended supportive care, fluids, rest.',
            doctorName: 'Dr. David Kim',
            createdAt: new Date('2024-04-12').toISOString(),
        },
        {
            patientId: 5,
            recordDate: new Date('2024-05-18').toISOString(),
            recordType: 'visit_note',
            title: 'Back Pain Evaluation',
            description: 'Patient reports 2-week history of lower back pain after lifting heavy boxes. Pain 6/10, worse with bending and lifting. No radiation to legs, no numbness or weakness. Physical exam shows paravertebral muscle spasm, limited range of motion. Straight leg raise negative. Diagnosed with mechanical low back pain. Prescribed muscle relaxant and physical therapy.',
            doctorName: 'Dr. Jennifer Walsh',
            createdAt: new Date('2024-05-18').toISOString(),
        },
        {
            patientId: 6,
            recordDate: new Date('2024-06-22').toISOString(),
            recordType: 'visit_note',
            title: 'Annual Physical Exam',
            description: 'Annual wellness examination. Patient reports excellent health, exercises regularly, follows Mediterranean diet. Vital signs normal: BP 118/75 mmHg, HR 65 bpm, BMI 23.2. Complete physical examination unremarkable. Updated immunizations, ordered age-appropriate screening tests. Counseled on continued healthy lifestyle.',
            doctorName: 'Dr. Robert Thompson',
            createdAt: new Date('2024-06-22').toISOString(),
        },
        {
            patientId: 7,
            recordDate: new Date('2024-07-28').toISOString(),
            recordType: 'visit_note',
            title: 'Hypertension Follow-up',
            description: 'Established patient with newly diagnosed hypertension. Started on amlodipine 5mg daily 6 weeks ago. Patient reports no side effects. Home BP readings improved to 132/80 mmHg average. Weight stable, following DASH diet. Physical exam stable. Continue current medication, recheck BP in 8 weeks.',
            doctorName: 'Dr. Lisa Patel',
            createdAt: new Date('2024-07-28').toISOString(),
        },
        {
            patientId: 8,
            recordDate: new Date('2024-08-25').toISOString(),
            recordType: 'visit_note',
            title: 'Diabetes Management',
            description: 'New diagnosis of Type 2 diabetes mellitus. Patient overwhelmed but motivated to make changes. Discussed pathophysiology, complications, and treatment goals. Started diabetes education, referred to nutritionist. Prescribed metformin 500mg BID. Emphasized importance of blood glucose monitoring and lifestyle modifications.',
            doctorName: 'Dr. James Wilson',
            createdAt: new Date('2024-08-25').toISOString(),
        },
        {
            patientId: 1,
            recordDate: new Date('2024-09-14').toISOString(),
            recordType: 'visit_note',
            title: 'Cold Symptoms',
            description: 'Patient presents with acute onset rhinorrhea, sneezing, and mild headache for 2 days. No fever, cough, or systemic symptoms. Physical exam shows clear nasal discharge, mildly injected conjunctiva. Throat and lungs normal. Diagnosed with allergic rhinitis vs. viral rhinitis. Recommended antihistamines and nasal saline irrigation.',
            doctorName: 'Dr. Sarah Johnson',
            createdAt: new Date('2024-09-14').toISOString(),
        },
        {
            patientId: 2,
            recordDate: new Date('2024-10-08').toISOString(),
            recordType: 'visit_note',
            title: 'Back Pain Evaluation',
            description: 'Follow-up for chronic lower back pain. Patient completed 6 weeks of physical therapy with moderate improvement. Pain now 4/10, functional capacity improved. Still has morning stiffness. Physical exam shows improved range of motion, less muscle spasm. Continue home exercise program, consider referral to pain management if no further improvement.',
            doctorName: 'Dr. Michael Chen',
            createdAt: new Date('2024-10-08').toISOString(),
        },
        {
            patientId: 3,
            recordDate: new Date('2024-11-16').toISOString(),
            recordType: 'visit_note',
            title: 'Annual Physical Exam',
            description: 'Comprehensive annual exam for patient with well-controlled diabetes and hypertension. Patient reports good energy, no new symptoms. Medications well-tolerated. BP 125/78 mmHg, BMI stable at 28.5. Foot exam normal, no signs of diabetic complications. Mammogram and colonoscopy up to date. Continue current management.',
            doctorName: 'Dr. Emily Rodriguez',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            patientId: 4,
            recordDate: new Date('2024-12-05').toISOString(),
            recordType: 'visit_note',
            title: 'Hypertension Follow-up',
            description: 'Routine hypertension management. Patient adherent to medications (lisinopril 20mg, HCTZ 25mg). Home BP readings well-controlled at 125/78 mmHg average. Weight loss of 8 pounds since last visit. No medication side effects. Labs pending. Continue current regimen, congratulated on lifestyle improvements.',
            doctorName: 'Dr. David Kim',
            createdAt: new Date('2024-12-05').toISOString(),
        },
        {
            patientId: 5,
            recordDate: new Date('2024-01-22').toISOString(),
            recordType: 'visit_note',
            title: 'Diabetes Management',
            description: 'Quarterly diabetes visit. Patient reports occasional mild hypoglycemic episodes, especially before meals. Adjusted insulin timing and carbohydrate counting. Reviewed sick day management and hypoglycemia treatment. Feet examination normal. Eye exam scheduled. A1C pending to assess overall control.',
            doctorName: 'Dr. Jennifer Walsh',
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            patientId: 6,
            recordDate: new Date('2024-03-30').toISOString(),
            recordType: 'visit_note',
            title: 'Cold Symptoms',
            description: 'Acute visit for upper respiratory symptoms. 4-day history of nasal congestion, productive cough with yellow sputum, mild chest discomfort. Low-grade fever 100.2°F. Physical exam shows purulent nasal discharge, rhonchi in both lungs. Diagnosed with acute bronchitis. Prescribed azithromycin and supportive care.',
            doctorName: 'Dr. Robert Thompson',
            createdAt: new Date('2024-03-30').toISOString(),
        },
        {
            patientId: 7,
            recordDate: new Date('2024-05-12').toISOString(),
            recordType: 'visit_note',
            title: 'Back Pain Evaluation',
            description: 'New complaint of acute lower back pain following gardening activities. Pain 8/10, sharp, radiating to right buttock. No leg weakness or numbness. Physical exam shows right-sided paravertebral muscle spasm, positive straight leg raise at 45 degrees. Diagnosed with acute lumbar strain with possible radiculopathy. Ordered MRI, prescribed NSAIDs.',
            doctorName: 'Dr. Lisa Patel',
            createdAt: new Date('2024-05-12').toISOString(),
        },
        {
            patientId: 8,
            recordDate: new Date('2024-07-20').toISOString(),
            recordType: 'visit_note',
            title: 'Annual Physical Exam',
            description: 'First annual physical for new patient. History significant for family history of diabetes and heart disease. Currently feeling well, no medications. Vital signs: BP 142/88 mmHg, BMI 29.8, otherwise normal exam. Discussed cardiovascular risk factors, recommended weight loss, ordered baseline labs including glucose and lipids.',
            doctorName: 'Dr. James Wilson',
            createdAt: new Date('2024-07-20').toISOString(),
        },
        {
            patientId: 1,
            recordDate: new Date('2024-11-28').toISOString(),
            recordType: 'visit_note',
            title: 'Hypertension Follow-up',
            description: 'Regular follow-up for well-controlled hypertension. Patient reports excellent medication compliance, regular exercise, and DASH diet adherence. Home BP log shows consistent readings 122-128/75-82 mmHg. Physical exam unremarkable. Labs show good kidney function. Continue current ACE inhibitor, next visit in 6 months.',
            doctorName: 'Dr. Sarah Johnson',
            createdAt: new Date('2024-11-28').toISOString(),
        },
        {
            patientId: 2,
            recordDate: new Date('2024-12-18').toISOString(),
            recordType: 'visit_note',
            title: 'Diabetes Management',
            description: 'Routine diabetes care visit. Patient reports improved glucose control with new medication regimen. Fewer episodes of hyperglycemia, no hypoglycemia. Home glucose logs show fasting 95-125 mg/dL, post-meal <180 mg/dL. Foot exam normal, monofilament testing intact. A1C improved to 6.8%. Continue current therapy.',
            doctorName: 'Dr. Michael Chen',
            createdAt: new Date('2024-12-18').toISOString(),
        },

        // Imaging (20% - 12 records)
        {
            patientId: 1,
            recordDate: new Date('2024-02-28').toISOString(),
            recordType: 'imaging',
            title: 'Chest X-Ray',
            description: 'Posteroanterior and lateral chest radiographs obtained for pre-operative clearance. Heart size normal, no cardiomegaly. Lungs are clear bilaterally with no evidence of infiltrate, effusion, or pneumothorax. No acute cardiopulmonary abnormalities identified. Cleared for elective surgery.',
            doctorName: 'Dr. Sarah Johnson',
            createdAt: new Date('2024-02-28').toISOString(),
        },
        {
            patientId: 3,
            recordDate: new Date('2024-04-18').toISOString(),
            recordType: 'imaging',
            title: 'MRI Knee',
            description: 'MRI right knee without contrast for chronic knee pain. Findings: Grade 2 medial meniscus tear with horizontal cleavage pattern. Moderate chondromalacia patella with Grade 2-3 cartilage loss. Mild joint effusion present. ACL and PCL intact. Recommend orthopedic consultation for possible arthroscopic meniscectomy.',
            doctorName: 'Dr. Emily Rodriguez',
            createdAt: new Date('2024-04-18').toISOString(),
        },
        {
            patientId: 5,
            recordDate: new Date('2024-06-08').toISOString(),
            recordType: 'imaging',
            title: 'Ultrasound Abdomen',
            description: 'Abdominal ultrasound for right upper quadrant pain. Gallbladder shows multiple echogenic foci consistent with cholelithiasis, largest stone measuring 1.2 cm. No gallbladder wall thickening or pericholecystic fluid. Liver, spleen, and kidneys appear normal. Common bile duct not dilated. Findings consistent with asymptomatic cholelithiasis.',
            doctorName: 'Dr. Jennifer Walsh',
            createdAt: new Date('2024-06-08').toISOString(),
        },
        {
            patientId: 7,
            recordDate: new Date('2024-08-14').toISOString(),
            recordType: 'imaging',
            title: 'Mammography',
            description: 'Bilateral screening mammography. Breast tissue shows scattered fibroglandular density (BI-RADS Category B). No suspicious masses, calcifications, or architectural distortion identified. Both breasts appear symmetric. BI-RADS Category 1 - Negative. Recommend routine annual screening mammography.',
            doctorName: 'Dr. Lisa Patel',
            createdAt: new Date('2024-08-14').toISOString(),
        },
        {
            patientId: 2,
            recordDate: new Date('2024-10-25').toISOString(),
            recordType: 'imaging',
            title: 'CT Scan Head',
            description: 'Non-contrast head CT for severe headaches and visual changes. No evidence of acute intracranial hemorrhage, mass effect, or midline shift. Ventricles are normal in size and configuration. No acute infarct identified. Mild age-related cerebral volume loss noted. Findings do not explain patient symptoms. Consider MRI brain with contrast.',
            doctorName: 'Dr. Michael Chen',
            createdAt: new Date('2024-10-25').toISOString(),
        },
        {
            patientId: 4,
            recordDate: new Date('2024-12-12').toISOString(),
            recordType: 'imaging',
            title: 'Chest X-Ray',
            description: 'Chest X-ray for persistent cough and shortness of breath. Bilateral lower lobe infiltrates consistent with pneumonia. Heart size mildly enlarged. No pleural effusions. Findings suggest community-acquired pneumonia. Recommend antibiotic therapy and follow-up chest X-ray in 2-3 weeks to ensure resolution.',
            doctorName: 'Dr. David Kim',
            createdAt: new Date('2024-12-12').toISOString(),
        },
        {
            patientId: 6,
            recordDate: new Date('2024-03-05').toISOString(),
            recordType: 'imaging',
            title: 'MRI Knee',
            description: 'Left knee MRI for sports injury evaluation. Small partial-thickness tear of the anterior cruciate ligament with surrounding edema. Medial and lateral menisci intact. Mild bone contusion in lateral femoral condyle. Moderate joint effusion. Recommend sports medicine consultation and possible arthroscopic repair.',
            doctorName: 'Dr. Robert Thompson',
            createdAt: new Date('2024-03-05').toISOString(),
        },
        {
            patientId: 8,
            recordDate: new Date('2024-05-22').toISOString(),
            recordType: 'imaging',
            title: 'Ultrasound Abdomen',
            description: 'Abdominal ultrasound for abnormal liver enzymes. Liver demonstrates increased echogenicity consistent with fatty infiltration. No focal hepatic lesions identified. Gallbladder, spleen, and kidneys normal. Portal vein flow is hepatopetal. Findings consistent with hepatic steatosis, likely related to diabetes and obesity.',
            doctorName: 'Dr. James Wilson',
            createdAt: new Date('2024-05-22').toISOString(),
        },
        {
            patientId: 1,
            recordDate: new Date('2024-07-11').toISOString(),
            recordType: 'imaging',
            title: 'Mammography',
            description: 'Annual screening mammography. Heterogeneously dense breast tissue (BI-RADS Category C). New 8mm irregular mass in upper outer quadrant of right breast with associated pleomorphic calcifications. BI-RADS Category 4 - Suspicious abnormality. Recommend stereotactic core needle biopsy.',
            doctorName: 'Dr. Sarah Johnson',
            createdAt: new Date('2024-07-11').toISOString(),
        },
        {
            patientId: 3,
            recordDate: new Date('2024-09-18').toISOString(),
            recordType: 'imaging',
            title: 'CT Scan Head',
            description: 'Head CT with contrast for evaluation of persistent headaches and neurological symptoms. Small hypodense lesion in left frontal lobe measuring 1.5 cm with minimal surrounding edema. No mass effect or hemorrhage. Differential includes primary brain tumor vs. metastasis. Recommend neurology consultation and possible brain MRI.',
            doctorName: 'Dr. Emily Rodriguez',
            createdAt: new Date('2024-09-18').toISOString(),
        },
        {
            patientId: 5,
            recordDate: new Date('2024-11-07').toISOString(),
            recordType: 'imaging',
            title: 'Chest X-Ray',
            description: 'Follow-up chest X-ray for previous pneumonia treatment. Complete resolution of bilateral lower lobe infiltrates. Heart size normal. No residual consolidation or pleural abnormalities. Successful treatment of community-acquired pneumonia. No further imaging needed unless symptoms recur.',
            doctorName: 'Dr. Jennifer Walsh',
            createdAt: new Date('2024-11-07').toISOString(),
        },
        {
            patientId: 7,
            recordDate: new Date('2024-12-28').toISOString(),
            recordType: 'imaging',
            title: 'Ultrasound Abdomen',
            description: 'Pelvic ultrasound for irregular menstrual bleeding. Uterus is normal in size and contour. Endometrial thickness measures 8mm, within normal limits for menstrual phase. Both ovaries visualized and appear normal with no cysts or masses. Small amount of free fluid in pelvis, likely physiologic. Normal pelvic ultrasound.',
            doctorName: 'Dr. Lisa Patel',
            createdAt: new Date('2024-12-28').toISOString(),
        },

        // Prescriptions (10% - 6 records)
        {
            patientId: 4,
            recordDate: new Date('2024-04-10').toISOString(),
            recordType: 'prescription',
            title: 'Metformin Prescription',
            description: 'Prescribed metformin 1000mg twice daily for Type 2 diabetes mellitus management. Patient counseled on taking with meals to reduce gastrointestinal side effects. Discussed importance of medication compliance for glycemic control. Blood glucose monitoring recommended. Follow-up in 3 months with repeat A1C.',
            doctorName: 'Dr. David Kim',
            createdAt: new Date('2024-04-10').toISOString(),
        },
        {
            patientId: 2,
            recordDate: new Date('2024-06-15').toISOString(),
            recordType: 'prescription',
            title: 'Blood Pressure Medication',
            description: 'Initiated lisinopril 10mg daily for newly diagnosed hypertension. Patient counseled on potential side effects including dry cough and angioedema. Emphasized importance of medication compliance and home blood pressure monitoring. Lifestyle modifications discussed. Follow-up in 4 weeks to assess response.',
            doctorName: 'Dr. Michael Chen',
            createdAt: new Date('2024-06-15').toISOString(),
        },
        {
            patientId: 6,
            recordDate: new Date('2024-08-28').toISOString(),
            recordType: 'prescription',
            title: 'Antibiotic Course',
            description: 'Prescribed azithromycin 500mg on day 1, then 250mg daily for 4 days for acute bacterial sinusitis. Patient counseled on completing full course despite symptom improvement. Discussed potential side effects including GI upset and drug interactions. Recommend probiotics during treatment. Return if symptoms worsen.',
            doctorName: 'Dr. Robert Thompson',
            createdAt: new Date('2024-08-28').toISOString(),
        },
        {
            patientId: 8,
            recordDate: new Date('2024-10-03').toISOString(),
            recordType: 'prescription',
            title: 'Metformin Prescription',
            description: 'Started metformin 500mg twice daily for newly diagnosed Type 2 diabetes. Initiated at lower dose to assess tolerance, plan to increase to 1000mg BID in 2 weeks if well-tolerated. Patient educated on taking with food, monitoring for lactic acidosis symptoms. Diabetes education referral made.',
            doctorName: 'Dr. James Wilson',
            createdAt: new Date('2024-10-03').toISOString(),
        },
        {
            patientId: 1,
            recordDate: new Date('2024-11-20').toISOString(),
            recordType: 'prescription',
            title: 'Blood Pressure Medication',
            description: 'Adjusted amlodipine from 5mg to 10mg daily for suboptimal blood pressure control. Patient tolerating current dose well with no peripheral edema. Discussed importance of medication timing and compliance. Home BP monitoring encouraged. Recheck blood pressure and labs in 6 weeks.',
            doctorName: 'Dr. Sarah Johnson',
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            patientId: 5,
            recordDate: new Date('2024-12-15').toISOString(),
            recordType: 'prescription',
            title: 'Antibiotic Course',
            description: 'Prescribed amoxicillin-clavulanate 875mg/125mg twice daily for 10 days for urinary tract infection. Patient counseled on completing full course and taking with food to reduce GI side effects. Increased fluid intake recommended. Follow-up urine culture in 1 week post-treatment completion.',
            doctorName: 'Dr. Jennifer Walsh',
            createdAt: new Date('2024-12-15').toISOString(),
        }
    ];

    await db.insert(medicalRecords).values(sampleMedicalRecords);
    
    console.log('✅ Medical records seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});