import { db } from '@/db';
import { patientAuditLog } from '@/db/schema';

async function main() {
    const sampleAuditLogs = [
        {
            patientId: 1,
            fieldChanged: 'phone',
            oldValue: '+27 82 456 7890',
            newValue: '+27 83 567 8901',
            changedBy: 'Admin Mary',
            reason: 'Patient requested update',
            createdAt: new Date('2024-07-15T09:30:00Z').toISOString(),
        },
        {
            patientId: 2,
            fieldChanged: 'email',
            oldValue: 'john.doe@gmail.com',
            newValue: 'john.doe@outlook.com',
            changedBy: 'Reception Desk',
            reason: 'Email address updated',
            createdAt: new Date('2024-07-20T14:15:00Z').toISOString(),
        },
        {
            patientId: 3,
            fieldChanged: 'medical_aid',
            oldValue: 'Discovery Health',
            newValue: 'Bonitas Medical Fund',
            changedBy: 'Dr. Smith',
            reason: 'New insurance coverage',
            createdAt: new Date('2024-08-01T11:45:00Z').toISOString(),
        },
        {
            patientId: 1,
            fieldChanged: 'medical_aid_number',
            oldValue: 'DH123456789',
            newValue: 'BM987654321',
            changedBy: 'Dr. Smith',
            reason: 'Insurance plan change',
            createdAt: new Date('2024-08-01T11:50:00Z').toISOString(),
        },
        {
            patientId: 4,
            fieldChanged: 'active',
            oldValue: 'false',
            newValue: 'true',
            changedBy: 'Nurse Johnson',
            reason: 'Account reactivation',
            createdAt: new Date('2024-08-05T08:20:00Z').toISOString(),
        },
        {
            patientId: 5,
            fieldChanged: 'last_name',
            oldValue: 'Smith',
            newValue: 'Johnson',
            changedBy: 'Admin John',
            reason: 'Marriage status change',
            createdAt: new Date('2024-08-10T16:30:00Z').toISOString(),
        },
        {
            patientId: 6,
            fieldChanged: 'passport_number',
            oldValue: 'A1234567',
            newValue: 'B9876543',
            changedBy: 'Reception Desk',
            reason: 'Passport renewal',
            createdAt: new Date('2024-08-12T10:15:00Z').toISOString(),
        },
        {
            patientId: 7,
            fieldChanged: 'phone',
            oldValue: '082 123 4567',
            newValue: '+27 84 234 5678',
            changedBy: 'Nurse Patricia',
            reason: 'Phone number changed',
            createdAt: new Date('2024-08-15T13:25:00Z').toISOString(),
        },
        {
            patientId: 8,
            fieldChanged: 'id_image_url',
            oldValue: null,
            newValue: '/uploads/id_docs/patient_8_id.jpg',
            changedBy: 'Dr. Williams',
            reason: 'Document verification',
            createdAt: new Date('2024-08-18T09:40:00Z').toISOString(),
        },
        {
            patientId: 9,
            fieldChanged: 'first_name',
            oldValue: 'Micheal',
            newValue: 'Michael',
            changedBy: 'Admin Mary',
            reason: 'Incorrect information corrected',
            createdAt: new Date('2024-08-20T15:10:00Z').toISOString(),
        },
        {
            patientId: 10,
            fieldChanged: 'email',
            oldValue: 'sarah.wilson@yahoo.com',
            newValue: 'sarah.wilson@gmail.com',
            changedBy: 'Reception Desk',
            reason: 'Contact preference update',
            createdAt: new Date('2024-08-22T11:05:00Z').toISOString(),
        },
        {
            patientId: 11,
            fieldChanged: 'medical_aid',
            oldValue: 'Momentum Health',
            newValue: 'Fedhealth',
            changedBy: 'Dr. Brown',
            reason: 'New insurance coverage',
            createdAt: new Date('2024-08-25T14:30:00Z').toISOString(),
        },
        {
            patientId: 12,
            fieldChanged: 'active',
            oldValue: 'true',
            newValue: 'false',
            changedBy: 'System Update',
            reason: 'Data cleanup',
            createdAt: new Date('2024-08-28T07:15:00Z').toISOString(),
        },
        {
            patientId: 13,
            fieldChanged: 'phone',
            oldValue: '011 234 5678',
            newValue: '+27 11 234 5678',
            changedBy: 'Nurse Linda',
            reason: 'System migration',
            createdAt: new Date('2024-08-30T12:45:00Z').toISOString(),
        },
        {
            patientId: 14,
            fieldChanged: 'medical_aid_number',
            oldValue: 'MM456789123',
            newValue: 'FH789123456',
            changedBy: 'Dr. Smith',
            reason: 'Insurance plan change',
            createdAt: new Date('2024-09-02T10:20:00Z').toISOString(),
        },
        {
            patientId: 15,
            fieldChanged: 'last_name',
            oldValue: 'Van Der Merwe',
            newValue: 'Van der Merwe',
            changedBy: 'Admin John',
            reason: 'Incorrect information corrected',
            createdAt: new Date('2024-09-05T16:55:00Z').toISOString(),
        },
        {
            patientId: 16,
            fieldChanged: 'email',
            oldValue: 'peter.jones@hotmail.com',
            newValue: 'p.jones@corporate.co.za',
            changedBy: 'Reception Desk',
            reason: 'Email address updated',
            createdAt: new Date('2024-09-08T08:35:00Z').toISOString(),
        },
        {
            patientId: 17,
            fieldChanged: 'id_image_url',
            oldValue: '/uploads/id_docs/patient_17_old.jpg',
            newValue: '/uploads/id_docs/patient_17_new.jpg',
            changedBy: 'Nurse Johnson',
            reason: 'Document verification',
            createdAt: new Date('2024-09-10T13:20:00Z').toISOString(),
        },
        {
            patientId: 18,
            fieldChanged: 'phone',
            oldValue: '083 987 6543',
            newValue: '+27 73 987 6543',
            changedBy: 'Dr. Williams',
            reason: 'Phone number changed',
            createdAt: new Date('2024-09-12T11:40:00Z').toISOString(),
        },
        {
            patientId: 19,
            fieldChanged: 'medical_aid',
            oldValue: 'Bestmed',
            newValue: 'Discovery Health',
            changedBy: 'Admin Mary',
            reason: 'New insurance coverage',
            createdAt: new Date('2024-09-15T15:15:00Z').toISOString(),
        },
        {
            patientId: 20,
            fieldChanged: 'passport_number',
            oldValue: 'C5678901',
            newValue: 'D2345678',
            changedBy: 'Reception Desk',
            reason: 'Passport renewal',
            createdAt: new Date('2024-09-18T09:25:00Z').toISOString(),
        },
        {
            patientId: 21,
            fieldChanged: 'active',
            oldValue: 'false',
            newValue: 'true',
            changedBy: 'Nurse Patricia',
            reason: 'Patient verification',
            createdAt: new Date('2024-09-20T14:10:00Z').toISOString(),
        },
        {
            patientId: 22,
            fieldChanged: 'first_name',
            oldValue: 'Catharine',
            newValue: 'Catherine',
            changedBy: 'Dr. Brown',
            reason: 'Incorrect information corrected',
            createdAt: new Date('2024-09-22T10:50:00Z').toISOString(),
        },
        {
            patientId: 23,
            fieldChanged: 'medical_aid_number',
            oldValue: 'BM123456789',
            newValue: 'DH987654321',
            changedBy: 'Admin John',
            reason: 'Insurance plan change',
            createdAt: new Date('2024-09-25T12:30:00Z').toISOString(),
        },
        {
            patientId: 24,
            fieldChanged: 'email',
            oldValue: 'robert.brown@mail.com',
            newValue: 'rob.brown@newmail.co.za',
            changedBy: 'System Update',
            reason: 'Contact preference update',
            createdAt: new Date('2024-09-28T16:45:00Z').toISOString(),
        },
        {
            patientId: 25,
            fieldChanged: 'phone',
            oldValue: '078 456 1234',
            newValue: '+27 79 456 1234',
            changedBy: 'Nurse Linda',
            reason: 'System migration',
            createdAt: new Date('2024-10-01T08:15:00Z').toISOString(),
        },
        {
            patientId: 26,
            fieldChanged: 'last_name',
            oldValue: 'Thompson',
            newValue: 'Davis',
            changedBy: 'Reception Desk',
            reason: 'Marriage status change',
            createdAt: new Date('2024-10-03T13:55:00Z').toISOString(),
        },
        {
            patientId: 27,
            fieldChanged: 'medical_aid',
            oldValue: 'Keyhealth',
            newValue: 'Momentum Health',
            changedBy: 'Dr. Smith',
            reason: 'New insurance coverage',
            createdAt: new Date('2024-10-05T11:20:00Z').toISOString(),
        },
        {
            patientId: 28,
            fieldChanged: 'id_image_url',
            oldValue: null,
            newValue: '/uploads/id_docs/patient_28_passport.jpg',
            changedBy: 'Nurse Johnson',
            reason: 'Document verification',
            createdAt: new Date('2024-10-08T15:40:00Z').toISOString(),
        },
        {
            patientId: 29,
            fieldChanged: 'active',
            oldValue: 'true',
            newValue: 'false',
            changedBy: 'Admin Mary',
            reason: 'Data cleanup',
            createdAt: new Date('2024-10-10T09:30:00Z').toISOString(),
        },
        {
            patientId: 30,
            fieldChanged: 'email',
            oldValue: 'lisa.white@domain.com',
            newValue: 'l.white@newdomain.co.za',
            changedBy: 'Dr. Williams',
            reason: 'Email address updated',
            createdAt: new Date('2024-10-12T14:25:00Z').toISOString(),
        },
        {
            patientId: 31,
            fieldChanged: 'phone',
            oldValue: '012 345 6789',
            newValue: '+27 12 345 6789',
            changedBy: 'Nurse Patricia',
            reason: 'Phone number changed',
            createdAt: new Date('2024-10-15T10:15:00Z').toISOString(),
        },
        {
            patientId: 32,
            fieldChanged: 'medical_aid_number',
            oldValue: 'KH789456123',
            newValue: 'MH123789456',
            changedBy: 'Reception Desk',
            reason: 'Insurance plan change',
            createdAt: new Date('2024-10-18T12:50:00Z').toISOString(),
        },
        {
            patientId: 33,
            fieldChanged: 'passport_number',
            oldValue: 'E3456789',
            newValue: 'F9876543',
            changedBy: 'Dr. Brown',
            reason: 'Passport renewal',
            createdAt: new Date('2024-10-20T16:10:00Z').toISOString(),
        },
        {
            patientId: 34,
            fieldChanged: 'first_name',
            oldValue: 'Johnathan',
            newValue: 'Jonathan',
            changedBy: 'Admin John',
            reason: 'Incorrect information corrected',
            createdAt: new Date('2024-10-22T08:45:00Z').toISOString(),
        },
        {
            patientId: 35,
            fieldChanged: 'medical_aid',
            oldValue: 'GEMS',
            newValue: 'Bonitas Medical Fund',
            changedBy: 'Nurse Linda',
            reason: 'New insurance coverage',
            createdAt: new Date('2024-10-25T13:35:00Z').toISOString(),
        },
        {
            patientId: 36,
            fieldChanged: 'active',
            oldValue: 'false',
            newValue: 'true',
            changedBy: 'System Update',
            reason: 'Account reactivation',
            createdAt: new Date('2024-10-28T11:05:00Z').toISOString(),
        },
        {
            patientId: 37,
            fieldChanged: 'email',
            oldValue: 'amanda.green@email.co.za',
            newValue: 'a.green@corporate.com',
            changedBy: 'Reception Desk',
            reason: 'Contact preference update',
            createdAt: new Date('2024-10-30T15:20:00Z').toISOString(),
        },
        {
            patientId: 38,
            fieldChanged: 'phone',
            oldValue: '084 123 9876',
            newValue: '+27 85 123 9876',
            changedBy: 'Dr. Smith',
            reason: 'System migration',
            createdAt: new Date('2024-11-01T09:15:00Z').toISOString(),
        },
        {
            patientId: 39,
            fieldChanged: 'last_name',
            oldValue: 'De Villiers',
            newValue: 'Devilliers',
            changedBy: 'Nurse Johnson',
            reason: 'Incorrect information corrected',
            createdAt: new Date('2024-11-03T14:40:00Z').toISOString(),
        },
        {
            patientId: 40,
            fieldChanged: 'id_image_url',
            oldValue: '/uploads/id_docs/patient_40_old.pdf',
            newValue: '/uploads/id_docs/patient_40_new.jpg',
            changedBy: 'Admin Mary',
            reason: 'Document verification',
            createdAt: new Date('2024-11-05T12:25:00Z').toISOString(),
        },
        {
            patientId: 41,
            fieldChanged: 'medical_aid_number',
            oldValue: 'GE456123789',
            newValue: 'BM789123456',
            changedBy: 'Dr. Williams',
            reason: 'Insurance plan change',
            createdAt: new Date('2024-11-08T10:55:00Z').toISOString(),
        },
        {
            patientId: 42,
            fieldChanged: 'phone',
            oldValue: '071 987 6543',
            newValue: '+27 72 987 6543',
            changedBy: 'Nurse Patricia',
            reason: 'Phone number changed',
            createdAt: new Date('2024-11-10T16:30:00Z').toISOString(),
        },
        {
            patientId: 43,
            fieldChanged: 'medical_aid',
            oldValue: 'Medshield',
            newValue: 'Fedhealth',
            changedBy: 'Reception Desk',
            reason: 'New insurance coverage',
            createdAt: new Date('2024-11-12T08:20:00Z').toISOString(),
        },
        {
            patientId: 44,
            fieldChanged: 'active',
            oldValue: 'true',
            newValue: 'false',
            changedBy: 'Dr. Brown',
            reason: 'Patient verification',
            createdAt: new Date('2024-11-15T13:45:00Z').toISOString(),
        },
        {
            patientId: 45,
            fieldChanged: 'email',
            oldValue: 'thomas.clark@mail.net',
            newValue: 't.clark@business.co.za',
            changedBy: 'Admin John',
            reason: 'Email address updated',
            createdAt: new Date('2024-11-18T11:10:00Z').toISOString(),
        },
        {
            patientId: 46,
            fieldChanged: 'passport_number',
            oldValue: 'G1234567',
            newValue: 'H7654321',
            changedBy: 'Nurse Linda',
            reason: 'Passport renewal',
            createdAt: new Date('2024-11-20T15:35:00Z').toISOString(),
        },
        {
            patientId: 47,
            fieldChanged: 'first_name',
            oldValue: 'Elizebeth',
            newValue: 'Elizabeth',
            changedBy: 'System Update',
            reason: 'Incorrect information corrected',
            createdAt: new Date('2024-11-22T09:50:00Z').toISOString(),
        },
        {
            patientId: 48,
            fieldChanged: 'phone',
            oldValue: '076 543 2109',
            newValue: '+27 76 543 2109',
            changedBy: 'Reception Desk',
            reason: 'System migration',
            createdAt: new Date('2024-11-25T14:15:00Z').toISOString(),
        },
        {
            patientId: 49,
            fieldChanged: 'medical_aid_number',
            oldValue: 'MS987654321',
            newValue: 'FH321654987',
            changedBy: 'Dr. Smith',
            reason: 'Insurance plan change',
            createdAt: new Date('2024-11-28T12:40:00Z').toISOString(),
        },
        {
            patientId: 50,
            fieldChanged: 'last_name',
            oldValue: 'Adams',
            newValue: 'Roberts',
            changedBy: 'Nurse Johnson',
            reason: 'Marriage status change',
            createdAt: new Date('2024-11-30T16:05:00Z').toISOString(),
        },
        {
            patientId: 51,
            fieldChanged: 'active',
            oldValue: 'false',
            newValue: 'true',
            changedBy: 'Admin Mary',
            reason: 'Account reactivation',
            createdAt: new Date('2024-12-02T10:25:00Z').toISOString(),
        },
        {
            patientId: 52,
            fieldChanged: 'email',
            oldValue: 'david.miller@webmail.com',
            newValue: 'd.miller@company.co.za',
            changedBy: 'Dr. Williams',
            reason: 'Contact preference update',
            createdAt: new Date('2024-12-05T13:50:00Z').toISOString(),
        },
        {
            patientId: 53,
            fieldChanged: 'id_image_url',
            oldValue: null,
            newValue: '/uploads/id_docs/patient_53_id_book.jpg',
            changedBy: 'Nurse Patricia',
            reason: 'Document verification',
            createdAt: new Date('2024-12-08T08:30:00Z').toISOString(),
        },
        {
            patientId: 54,
            fieldChanged: 'medical_aid',
            oldValue: 'Profmed',
            newValue: 'Discovery Health',
            changedBy: 'Reception Desk',
            reason: 'New insurance coverage',
            createdAt: new Date('2024-12-10T15:45:00Z').toISOString(),
        },
        {
            patientId: 55,
            fieldChanged: 'phone',
            oldValue: '082 654 3210',
            newValue: '+27 83 654 3210',
            changedBy: 'Dr. Brown',
            reason: 'Phone number changed',
            createdAt: new Date('2024-12-12T11:20:00Z').toISOString(),
        },
        {
            patientId: 56,
            fieldChanged: 'medical_aid_number',
            oldValue: 'PM159753486',
            newValue: 'DH486753159',
            changedBy: 'Admin John',
            reason: 'Insurance plan change',
            createdAt: new Date('2024-12-15T14:35:00Z').toISOString(),
        },
        {
            patientId: 57,
            fieldChanged: 'first_name',
            oldValue: 'Barbra',
            newValue: 'Barbara',
            changedBy: 'Nurse Linda',
            reason: 'Incorrect information corrected',
            createdAt: new Date('2024-12-18T09:40:00Z').toISOString(),
        },
        {
            patientId: 58,
            fieldChanged: 'passport_number',
            oldValue: 'I9876543',
            newValue: 'J1234567',
            changedBy: 'System Update',
            reason: 'Passport renewal',
            createdAt: new Date('2024-12-20T12:15:00Z').toISOString(),
        },
        {
            patientId: 59,
            fieldChanged: 'active',
            oldValue: 'true',
            newValue: 'false',
            changedBy: 'Reception Desk',
            reason: 'Data cleanup',
            createdAt: new Date('2024-12-22T16:50:00Z').toISOString(),
        },
        {
            patientId: 60,
            fieldChanged: 'email',
            oldValue: 'susan.taylor@oldmail.co.za',
            newValue: 's.taylor@newprovider.com',
            changedBy: 'Dr. Smith',
            reason: 'Email address updated',
            createdAt: new Date('2024-12-25T10:10:00Z').toISOString(),
        },
        {
            patientId: 1,
            fieldChanged: 'id_image_url',
            oldValue: '/uploads/id_docs/patient_1_temp.jpg',
            newValue: '/uploads/id_docs/patient_1_verified.jpg',
            changedBy: 'Nurse Johnson',
            reason: 'Document verification',
            createdAt: new Date('2024-12-28T13:25:00Z').toISOString(),
        },
        {
            patientId: 15,
            fieldChanged: 'phone',
            oldValue: '+27 11 234 5678',
            newValue: '+27 81 234 5678',
            changedBy: 'Admin Mary',
            reason: 'Phone number changed',
            createdAt: new Date('2024-12-30T15:40:00Z').toISOString(),
        },
        {
            patientId: 32,
            fieldChanged: 'medical_aid',
            oldValue: 'Momentum Health',
            newValue: 'Bestmed',
            changedBy: 'Dr. Williams',
            reason: 'New insurance coverage',
            createdAt: new Date('2025-01-02T09:15:00Z').toISOString(),
        },
        {
            patientId: 18,
            fieldChanged: 'active',
            oldValue: 'false',
            newValue: 'true',
            changedBy: 'Nurse Patricia',
            reason: 'Patient verification',
            createdAt: new Date('2025-01-05T11:30:00Z').toISOString(),
        },
        {
            patientId: 45,
            fieldChanged: 'last_name',
            oldValue: 'Clark',
            newValue: 'Clarke',
            changedBy: 'Reception Desk',
            reason: 'Incorrect information corrected',
            createdAt: new Date('2025-01-08T14:20:00Z').toISOString(),
        },
        {
            patientId: 27,
            fieldChanged: 'medical_aid_number',
            oldValue: 'MH123789456',
            newValue: 'MH456789123',
            changedBy: 'Dr. Brown',
            reason: 'Patient requested update',
            createdAt: new Date('2025-01-10T16:45:00Z').toISOString(),
        },
        {
            patientId: 39,
            fieldChanged: 'email',
            oldValue: 'k.devilliers@old.co.za',
            newValue: 'k.devilliers@updated.com',
            changedBy: 'Admin John',
            reason: 'Contact preference update',
            createdAt: new Date('2025-01-12T08:55:00Z').toISOString(),
        },
        {
            patientId: 6,
            fieldChanged: 'phone',
            oldValue: '+27 74 987 6543',
            newValue: '+27 75 987 6543',
            changedBy: 'Nurse Linda',
            reason: 'Phone number changed',
            createdAt: new Date('2025-01-15T12:10:00Z').toISOString(),
        },
        {
            patientId: 52,
            fieldChanged: 'id_image_url',
            oldValue: '/uploads/id_docs/patient_52_draft.pdf',
            newValue: '/uploads/id_docs/patient_52_final.jpg',
            changedBy: 'System Update',
            reason: 'Document verification',
            createdAt: new Date('2025-01-18T10:35:00Z').toISOString(),
        },
        {
            patientId: 11,
            fieldChanged: 'medical_aid',
            oldValue: 'Fedhealth',
            newValue: 'GEMS',
            changedBy: 'Reception Desk',
            reason: 'New insurance coverage',
            createdAt: new Date('2025-01-20T15:05:00Z').toISOString(),
        },
        {
            patientId: 33,
            fieldChanged: 'active',
            oldValue: 'true',
            newValue: 'false',
            changedBy: 'Dr. Smith',
            reason: 'Data cleanup',
            createdAt: new Date('2025-01-22T09:20:00Z').toISOString(),
        },
        {
            patientId: 24,
            fieldChanged: 'first_name',
            oldValue: 'Robert',
            newValue: 'Rob',
            changedBy: 'Nurse Johnson',
            reason: 'Patient requested update',
            createdAt: new Date('2025-01-25T13:40:00Z').toISOString(),
        },
        {
            patientId: 47,
            fieldChanged: 'passport_number',
            oldValue: 'H7654321',
            newValue: 'K1357924',
            changedBy: 'Admin Mary',
            reason: 'Passport renewal',
            createdAt: new Date('2025-01-28T11:15:00Z').toISOString(),
        },
        {
            patientId: 8,
            fieldChanged: 'medical_aid_number',
            oldValue: 'DH987123456',
            newValue: 'DH456123789',
            changedBy: 'Dr. Williams',
            reason: 'Insurance plan change',
            createdAt: new Date('2025-01-30T14:50:00Z').toISOString(),
        },
        {
            patientId: 56,
            fieldChanged: 'phone',
            oldValue: '+27 83 654 3210',
            newValue: '+27 84 654 3210',
            changedBy: 'Nurse Patricia',
            reason: 'Phone number changed',
            createdAt: new Date('2025-02-01T16:25:00Z').toISOString(),
        },
        {
            patientId: 41,
            fieldChanged: 'email',
            oldValue: 'mary.johnson@email.co.za',
            newValue: 'm.johnson@corporate.net',
            changedBy: 'Reception Desk',
            reason: 'Email address updated',
            createdAt: new Date('2025-02-03T08:40:00Z').toISOString(),
        },
        {
            patientId: 29,
            fieldChanged: 'active',
            oldValue: 'false',
            newValue: 'true',
            changedBy: 'Dr. Brown',
            reason: 'Account reactivation',
            createdAt: new Date('2025-02-05T12:05:00Z').toISOString(),
        },
        {
            patientId: 14,
            fieldChanged: 'last_name',
            oldValue: 'Anderson',
            newValue: 'Andersen',
            changedBy: 'Admin John',
            reason: 'Incorrect information corrected',
            createdAt: new Date('2025-02-08T15:30:00Z').toISOString(),
        },
        {
            patientId: 37,
            fieldChanged: 'medical_aid',
            oldValue: 'Bonitas Medical Fund',
            newValue: 'Keyhealth',
            changedBy: 'Nurse Linda',
            reason: 'New insurance coverage',
            createdAt: new Date('2025-02-10T10:45:00Z').toISOString(),
        },
        {
            patientId: 22,
            fieldChanged: 'id_image_url',
            oldValue: null,
            newValue: '/uploads/id_docs/patient_22_smartcard.jpg',
            changedBy: 'System Update',
            reason: 'Document verification',
            createdAt: new Date('2025-02-12T13:20:00Z').toISOString(),
        },
        {
            patientId: 50,
            fieldChanged: 'medical_aid_number',
            oldValue: 'FH321654987',
            newValue: 'KH987321654',
            changedBy: 'Reception Desk',
            reason: 'Insurance plan change',
            createdAt: new Date('2025-02-15T09:55:00Z').toISOString(),
        }
    ];

    await db.insert(patientAuditLog).values(sampleAuditLogs);
    
    console.log('✅ Patient audit log seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});