import { db } from '@/db';
import { prescriptions } from '@/db/schema';

async function main() {
    const samplePrescriptions = [
        {
            patientId: 1,
            medicationName: 'Metformin',
            dosage: '500mg',
            frequency: 'Twice daily',
            startDate: new Date('2023-08-15').toISOString(),
            endDate: null,
            doctorName: 'Dr. Sarah Johnson',
            status: 'active',
            createdAt: new Date('2023-08-15').toISOString(),
        },
        {
            patientId: 1,
            medicationName: 'Lisinopril',
            dosage: '10mg',
            frequency: 'Once daily',
            startDate: new Date('2023-09-01').toISOString(),
            endDate: null,
            doctorName: 'Dr. Sarah Johnson',
            status: 'active',
            createdAt: new Date('2023-09-01').toISOString(),
        },
        {
            patientId: 2,
            medicationName: 'Atorvastatin',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2023-07-20').toISOString(),
            endDate: null,
            doctorName: 'Dr. Michael Chen',
            status: 'active',
            createdAt: new Date('2023-07-20').toISOString(),
        },
        {
            patientId: 2,
            medicationName: 'Amoxicillin',
            dosage: '500mg',
            frequency: 'Three times daily',
            startDate: new Date('2024-01-10').toISOString(),
            endDate: new Date('2024-01-17').toISOString(),
            doctorName: 'Dr. Michael Chen',
            status: 'expired',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            patientId: 3,
            medicationName: 'Omeprazole',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2023-10-05').toISOString(),
            endDate: null,
            doctorName: 'Dr. Emily Rodriguez',
            status: 'active',
            createdAt: new Date('2023-10-05').toISOString(),
        },
        {
            patientId: 3,
            medicationName: 'Amlodipine',
            dosage: '5mg',
            frequency: 'Once daily',
            startDate: new Date('2023-09-15').toISOString(),
            endDate: null,
            doctorName: 'Dr. Emily Rodriguez',
            status: 'active',
            createdAt: new Date('2023-09-15').toISOString(),
        },
        {
            patientId: 4,
            medicationName: 'Ibuprofen',
            dosage: '400mg',
            frequency: 'As needed',
            startDate: new Date('2024-01-05').toISOString(),
            endDate: new Date('2024-01-19').toISOString(),
            doctorName: 'Dr. Robert Kim',
            status: 'expired',
            createdAt: new Date('2024-01-05').toISOString(),
        },
        {
            patientId: 4,
            medicationName: 'Prednisone',
            dosage: '10mg',
            frequency: 'Once daily',
            startDate: new Date('2023-12-01').toISOString(),
            endDate: new Date('2023-12-15').toISOString(),
            doctorName: 'Dr. Robert Kim',
            status: 'expired',
            createdAt: new Date('2023-12-01').toISOString(),
        },
        {
            patientId: 5,
            medicationName: 'Metformin',
            dosage: '850mg',
            frequency: 'Twice daily',
            startDate: new Date('2023-06-10').toISOString(),
            endDate: null,
            doctorName: 'Dr. Lisa Thompson',
            status: 'active',
            createdAt: new Date('2023-06-10').toISOString(),
        },
        {
            patientId: 5,
            medicationName: 'Atorvastatin',
            dosage: '40mg',
            frequency: 'Once daily',
            startDate: new Date('2023-08-25').toISOString(),
            endDate: null,
            doctorName: 'Dr. Lisa Thompson',
            status: 'active',
            createdAt: new Date('2023-08-25').toISOString(),
        },
        {
            patientId: 6,
            medicationName: 'Lisinopril',
            dosage: '5mg',
            frequency: 'Once daily',
            startDate: new Date('2023-11-10').toISOString(),
            endDate: null,
            doctorName: 'Dr. James Wilson',
            status: 'active',
            createdAt: new Date('2023-11-10').toISOString(),
        },
        {
            patientId: 6,
            medicationName: 'Amoxicillin',
            dosage: '250mg',
            frequency: 'Every 8 hours',
            startDate: new Date('2023-12-20').toISOString(),
            endDate: new Date('2023-12-30').toISOString(),
            doctorName: 'Dr. James Wilson',
            status: 'expired',
            createdAt: new Date('2023-12-20').toISOString(),
        },
        {
            patientId: 7,
            medicationName: 'Omeprazole',
            dosage: '40mg',
            frequency: 'Once daily',
            startDate: new Date('2023-09-05').toISOString(),
            endDate: null,
            doctorName: 'Dr. Maria Garcia',
            status: 'active',
            createdAt: new Date('2023-09-05').toISOString(),
        },
        {
            patientId: 7,
            medicationName: 'Amlodipine',
            dosage: '10mg',
            frequency: 'Once daily',
            startDate: new Date('2023-10-15').toISOString(),
            endDate: null,
            doctorName: 'Dr. Maria Garcia',
            status: 'active',
            createdAt: new Date('2023-10-15').toISOString(),
        },
        {
            patientId: 8,
            medicationName: 'Ibuprofen',
            dosage: '600mg',
            frequency: 'Every 6 hours',
            startDate: new Date('2024-01-15').toISOString(),
            endDate: new Date('2024-01-22').toISOString(),
            doctorName: 'Dr. David Lee',
            status: 'expired',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            patientId: 8,
            medicationName: 'Prednisone',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2023-11-20').toISOString(),
            endDate: new Date('2023-12-05').toISOString(),
            doctorName: 'Dr. David Lee',
            status: 'discontinued',
            createdAt: new Date('2023-11-20').toISOString(),
        },
        {
            patientId: 9,
            medicationName: 'Metformin',
            dosage: '1000mg',
            frequency: 'Twice daily',
            startDate: new Date('2023-05-15').toISOString(),
            endDate: null,
            doctorName: 'Dr. Jennifer Brown',
            status: 'active',
            createdAt: new Date('2023-05-15').toISOString(),
        },
        {
            patientId: 9,
            medicationName: 'Omeprazole',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2023-07-10').toISOString(),
            endDate: null,
            doctorName: 'Dr. Jennifer Brown',
            status: 'active',
            createdAt: new Date('2023-07-10').toISOString(),
        },
        {
            patientId: 10,
            medicationName: 'Atorvastatin',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2023-08-01').toISOString(),
            endDate: null,
            doctorName: 'Dr. Andrew Miller',
            status: 'active',
            createdAt: new Date('2023-08-01').toISOString(),
        },
        {
            patientId: 10,
            medicationName: 'Lisinopril',
            dosage: '10mg',
            frequency: 'Once daily',
            startDate: new Date('2023-09-20').toISOString(),
            endDate: null,
            doctorName: 'Dr. Andrew Miller',
            status: 'active',
            createdAt: new Date('2023-09-20').toISOString(),
        },
        {
            patientId: 11,
            medicationName: 'Amlodipine',
            dosage: '5mg',
            frequency: 'Once daily',
            startDate: new Date('2023-06-25').toISOString(),
            endDate: null,
            doctorName: 'Dr. Susan Davis',
            status: 'active',
            createdAt: new Date('2023-06-25').toISOString(),
        },
        {
            patientId: 11,
            medicationName: 'Amoxicillin',
            dosage: '875mg',
            frequency: 'Twice daily',
            startDate: new Date('2023-12-15').toISOString(),
            endDate: new Date('2023-12-25').toISOString(),
            doctorName: 'Dr. Susan Davis',
            status: 'expired',
            createdAt: new Date('2023-12-15').toISOString(),
        },
        {
            patientId: 12,
            medicationName: 'Omeprazole',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2023-10-01').toISOString(),
            endDate: null,
            doctorName: 'Dr. Kevin Wang',
            status: 'active',
            createdAt: new Date('2023-10-01').toISOString(),
        },
        {
            patientId: 12,
            medicationName: 'Ibuprofen',
            dosage: '200mg',
            frequency: 'As needed',
            startDate: new Date('2024-01-08').toISOString(),
            endDate: new Date('2024-01-15').toISOString(),
            doctorName: 'Dr. Kevin Wang',
            status: 'expired',
            createdAt: new Date('2024-01-08').toISOString(),
        },
        {
            patientId: 13,
            medicationName: 'Prednisone',
            dosage: '5mg',
            frequency: 'Once daily',
            startDate: new Date('2023-08-10').toISOString(),
            endDate: new Date('2023-09-10').toISOString(),
            doctorName: 'Dr. Rachel Green',
            status: 'discontinued',
            createdAt: new Date('2023-08-10').toISOString(),
        },
        {
            patientId: 13,
            medicationName: 'Metformin',
            dosage: '500mg',
            frequency: 'Twice daily',
            startDate: new Date('2023-11-01').toISOString(),
            endDate: null,
            doctorName: 'Dr. Rachel Green',
            status: 'active',
            createdAt: new Date('2023-11-01').toISOString(),
        },
        {
            patientId: 14,
            medicationName: 'Atorvastatin',
            dosage: '40mg',
            frequency: 'Once daily',
            startDate: new Date('2023-07-15').toISOString(),
            endDate: null,
            doctorName: 'Dr. Mark Taylor',
            status: 'active',
            createdAt: new Date('2023-07-15').toISOString(),
        },
        {
            patientId: 14,
            medicationName: 'Lisinopril',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2023-08-20').toISOString(),
            endDate: null,
            doctorName: 'Dr. Mark Taylor',
            status: 'active',
            createdAt: new Date('2023-08-20').toISOString(),
        },
        {
            patientId: 15,
            medicationName: 'Amlodipine',
            dosage: '10mg',
            frequency: 'Once daily',
            startDate: new Date('2023-09-10').toISOString(),
            endDate: null,
            doctorName: 'Dr. Laura Anderson',
            status: 'active',
            createdAt: new Date('2023-09-10').toISOString(),
        },
        {
            patientId: 15,
            medicationName: 'Amoxicillin',
            dosage: '500mg',
            frequency: 'Three times daily',
            startDate: new Date('2024-01-20').toISOString(),
            endDate: new Date('2024-01-30').toISOString(),
            doctorName: 'Dr. Laura Anderson',
            status: 'expired',
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            patientId: 16,
            medicationName: 'Omeprazole',
            dosage: '40mg',
            frequency: 'Once daily',
            startDate: new Date('2023-06-01').toISOString(),
            endDate: null,
            doctorName: 'Dr. Peter Clark',
            status: 'active',
            createdAt: new Date('2023-06-01').toISOString(),
        },
        {
            patientId: 16,
            medicationName: 'Ibuprofen',
            dosage: '400mg',
            frequency: 'Every 6 hours',
            startDate: new Date('2023-12-10').toISOString(),
            endDate: new Date('2023-12-17').toISOString(),
            doctorName: 'Dr. Peter Clark',
            status: 'expired',
            createdAt: new Date('2023-12-10').toISOString(),
        },
        {
            patientId: 17,
            medicationName: 'Prednisone',
            dosage: '15mg',
            frequency: 'Once daily',
            startDate: new Date('2023-10-20').toISOString(),
            endDate: new Date('2023-11-20').toISOString(),
            doctorName: 'Dr. Nancy White',
            status: 'discontinued',
            createdAt: new Date('2023-10-20').toISOString(),
        },
        {
            patientId: 17,
            medicationName: 'Metformin',
            dosage: '750mg',
            frequency: 'Twice daily',
            startDate: new Date('2023-12-01').toISOString(),
            endDate: null,
            doctorName: 'Dr. Nancy White',
            status: 'active',
            createdAt: new Date('2023-12-01').toISOString(),
        },
        {
            patientId: 18,
            medicationName: 'Atorvastatin',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2023-08-05').toISOString(),
            endDate: null,
            doctorName: 'Dr. Thomas Harris',
            status: 'active',
            createdAt: new Date('2023-08-05').toISOString(),
        },
        {
            patientId: 18,
            medicationName: 'Lisinopril',
            dosage: '15mg',
            frequency: 'Once daily',
            startDate: new Date('2023-09-15').toISOString(),
            endDate: null,
            doctorName: 'Dr. Thomas Harris',
            status: 'active',
            createdAt: new Date('2023-09-15').toISOString(),
        },
        {
            patientId: 19,
            medicationName: 'Amlodipine',
            dosage: '7.5mg',
            frequency: 'Once daily',
            startDate: new Date('2023-07-01').toISOString(),
            endDate: null,
            doctorName: 'Dr. Karen Lewis',
            status: 'active',
            createdAt: new Date('2023-07-01').toISOString(),
        },
        {
            patientId: 19,
            medicationName: 'Amoxicillin',
            dosage: '625mg',
            frequency: 'Twice daily',
            startDate: new Date('2023-11-25').toISOString(),
            endDate: new Date('2023-12-05').toISOString(),
            doctorName: 'Dr. Karen Lewis',
            status: 'expired',
            createdAt: new Date('2023-11-25').toISOString(),
        },
        {
            patientId: 20,
            medicationName: 'Omeprazole',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2023-05-20').toISOString(),
            endDate: null,
            doctorName: 'Dr. Steven Young',
            status: 'active',
            createdAt: new Date('2023-05-20').toISOString(),
        },
        {
            patientId: 20,
            medicationName: 'Ibuprofen',
            dosage: '800mg',
            frequency: 'As needed',
            startDate: new Date('2024-01-12').toISOString(),
            endDate: new Date('2024-01-19').toISOString(),
            doctorName: 'Dr. Steven Young',
            status: 'expired',
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            patientId: 3,
            medicationName: 'Prednisone',
            dosage: '10mg',
            frequency: 'Once daily',
            startDate: new Date('2023-08-15').toISOString(),
            endDate: new Date('2023-09-15').toISOString(),
            doctorName: 'Dr. Emily Rodriguez',
            status: 'discontinued',
            createdAt: new Date('2023-08-15').toISOString(),
        },
        {
            patientId: 7,
            medicationName: 'Metformin',
            dosage: '500mg',
            frequency: 'Twice daily',
            startDate: new Date('2024-01-05').toISOString(),
            endDate: null,
            doctorName: 'Dr. Maria Garcia',
            status: 'active',
            createdAt: new Date('2024-01-05').toISOString(),
        },
        {
            patientId: 12,
            medicationName: 'Atorvastatin',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2024-01-10').toISOString(),
            endDate: null,
            doctorName: 'Dr. Kevin Wang',
            status: 'active',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            patientId: 6,
            medicationName: 'Omeprazole',
            dosage: '20mg',
            frequency: 'Once daily',
            startDate: new Date('2024-01-15').toISOString(),
            endDate: null,
            doctorName: 'Dr. James Wilson',
            status: 'active',
            createdAt: new Date('2024-01-15').toISOString(),
        }
    ];

    await db.insert(prescriptions).values(samplePrescriptions);
    
    console.log('✅ Prescriptions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});