import { db } from '@/db';
import { staff } from '@/db/schema';

async function main() {
    const sampleStaff = [
        // Admin Staff (2)
        {
            firstName: 'Sarah',
            lastName: 'Williams',
            email: 'sarah.williams@clinic.com',
            phone: '(555) 101-2001',
            role: 'admin',
            department: 'Administration',
            hireDate: new Date('2022-03-15').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-03-15').toISOString(),
            updatedAt: new Date('2022-03-15').toISOString(),
        },
        {
            firstName: 'Michael',
            lastName: 'Chen',
            email: 'michael.chen@clinic.com',
            phone: '(555) 101-2002',
            role: 'admin',
            department: 'Administration',
            hireDate: new Date('2021-11-08').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-11-08').toISOString(),
            updatedAt: new Date('2021-11-08').toISOString(),
        },
        // Doctors (7)
        {
            firstName: 'Dr. Emily',
            lastName: 'Rodriguez',
            email: 'emily.rodriguez@clinic.com',
            phone: '(555) 201-3001',
            role: 'doctor',
            department: 'Cardiology',
            hireDate: new Date('2021-08-12').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-08-12').toISOString(),
            updatedAt: new Date('2021-08-12').toISOString(),
        },
        {
            firstName: 'Dr. James',
            lastName: 'Thompson',
            email: 'james.thompson@clinic.com',
            phone: '(555) 201-3002',
            role: 'doctor',
            department: 'General Medicine',
            hireDate: new Date('2022-01-20').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-01-20').toISOString(),
            updatedAt: new Date('2022-01-20').toISOString(),
        },
        {
            firstName: 'Dr. Lisa',
            lastName: 'Park',
            email: 'lisa.park@clinic.com',
            phone: '(555) 201-3003',
            role: 'doctor',
            department: 'Pediatrics',
            hireDate: new Date('2021-09-30').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-09-30').toISOString(),
            updatedAt: new Date('2021-09-30').toISOString(),
        },
        {
            firstName: 'Dr. Robert',
            lastName: 'Anderson',
            email: 'robert.anderson@clinic.com',
            phone: '(555) 201-3004',
            role: 'doctor',
            department: 'Orthopedics',
            hireDate: new Date('2022-05-18').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-05-18').toISOString(),
            updatedAt: new Date('2022-05-18').toISOString(),
        },
        {
            firstName: 'Dr. Maria',
            lastName: 'Garcia',
            email: 'maria.garcia@clinic.com',
            phone: '(555) 201-3005',
            role: 'doctor',
            department: 'Dermatology',
            hireDate: new Date('2021-12-03').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-12-03').toISOString(),
            updatedAt: new Date('2021-12-03').toISOString(),
        },
        {
            firstName: 'Dr. David',
            lastName: 'Kumar',
            email: 'david.kumar@clinic.com',
            phone: '(555) 201-3006',
            role: 'doctor',
            department: 'Neurology',
            hireDate: new Date('2022-02-14').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-02-14').toISOString(),
            updatedAt: new Date('2022-02-14').toISOString(),
        },
        {
            firstName: 'Dr. Jennifer',
            lastName: 'Wright',
            email: 'jennifer.wright@clinic.com',
            phone: '(555) 201-3007',
            role: 'doctor',
            department: 'Mental Health',
            hireDate: new Date('2021-10-25').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-10-25').toISOString(),
            updatedAt: new Date('2021-10-25').toISOString(),
        },
        // Nurses (5)
        {
            firstName: 'Amanda',
            lastName: 'Johnson',
            email: 'amanda.johnson@clinic.com',
            phone: '(555) 301-4001',
            role: 'nurse',
            department: 'Emergency',
            hireDate: new Date('2021-07-15').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-07-15').toISOString(),
            updatedAt: new Date('2021-07-15').toISOString(),
        },
        {
            firstName: 'Rachel',
            lastName: 'Davis',
            email: 'rachel.davis@clinic.com',
            phone: '(555) 301-4002',
            role: 'nurse',
            department: 'Cardiology',
            hireDate: new Date('2022-04-22').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-04-22').toISOString(),
            updatedAt: new Date('2022-04-22').toISOString(),
        },
        {
            firstName: 'Karen',
            lastName: 'Miller',
            email: 'karen.miller@clinic.com',
            phone: '(555) 301-4003',
            role: 'nurse',
            department: 'Pediatrics',
            hireDate: new Date('2022-01-10').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-01-10').toISOString(),
            updatedAt: new Date('2022-01-10').toISOString(),
        },
        {
            firstName: 'Nicole',
            lastName: 'Wilson',
            email: 'nicole.wilson@clinic.com',
            phone: '(555) 301-4004',
            role: 'nurse',
            department: 'General Medicine',
            hireDate: new Date('2021-11-18').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-11-18').toISOString(),
            updatedAt: new Date('2021-11-18').toISOString(),
        },
        {
            firstName: 'Patricia',
            lastName: 'Brown',
            email: 'patricia.brown@clinic.com',
            phone: '(555) 301-4005',
            role: 'nurse',
            department: 'Orthopedics',
            hireDate: new Date('2022-06-08').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-06-08').toISOString(),
            updatedAt: new Date('2022-06-08').toISOString(),
        },
        // Receptionists (3)
        {
            firstName: 'Jessica',
            lastName: 'Taylor',
            email: 'jessica.taylor@clinic.com',
            phone: '(555) 401-5001',
            role: 'receptionist',
            department: 'Front Desk',
            hireDate: new Date('2022-03-07').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-03-07').toISOString(),
            updatedAt: new Date('2022-03-07').toISOString(),
        },
        {
            firstName: 'Ashley',
            lastName: 'Martinez',
            email: 'ashley.martinez@clinic.com',
            phone: '(555) 401-5002',
            role: 'receptionist',
            department: 'Front Desk',
            hireDate: new Date('2021-09-12').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-09-12').toISOString(),
            updatedAt: new Date('2021-09-12').toISOString(),
        },
        {
            firstName: 'Michelle',
            lastName: 'Lee',
            email: 'michelle.lee@clinic.com',
            phone: '(555) 401-5003',
            role: 'receptionist',
            department: 'Front Desk',
            hireDate: new Date('2022-07-25').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-07-25').toISOString(),
            updatedAt: new Date('2022-07-25').toISOString(),
        },
        // Managers (2)
        {
            firstName: 'Christopher',
            lastName: 'White',
            email: 'christopher.white@clinic.com',
            phone: '(555) 501-6001',
            role: 'manager',
            department: 'Operations',
            hireDate: new Date('2021-06-01').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-06-01').toISOString(),
            updatedAt: new Date('2021-06-01').toISOString(),
        },
        {
            firstName: 'Laura',
            lastName: 'Jackson',
            email: 'laura.jackson@clinic.com',
            phone: '(555) 501-6002',
            role: 'manager',
            department: 'Patient Services',
            hireDate: new Date('2021-08-30').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2021-08-30').toISOString(),
            updatedAt: new Date('2021-08-30').toISOString(),
        },
        // Lab Technician (1)
        {
            firstName: 'Brian',
            lastName: 'Clark',
            email: 'brian.clark@clinic.com',
            phone: '(555) 601-7001',
            role: 'lab_technician',
            department: 'Laboratory',
            hireDate: new Date('2022-02-28').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-02-28').toISOString(),
            updatedAt: new Date('2022-02-28').toISOString(),
        }
    ];

    await db.insert(staff).values(sampleStaff);
    
    console.log('✅ Staff seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});