import { db } from '@/db';
import { staff } from '@/db/schema';

async function main() {
    const sampleStaff = [
        // Admin Staff (2)
        {
            firstName: 'Robert',
            lastName: 'Kim',
            email: 'robert.kim@clinic.com',
            phone: '(555) 201-3456',
            role: 'admin',
            department: 'Administration',
            hireDate: new Date('2022-03-15').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-03-15').toISOString(),
            updatedAt: new Date('2022-03-15').toISOString(),
        },
        {
            firstName: 'Jennifer',
            lastName: 'Thompson',
            email: 'jennifer.thompson@clinic.com',
            phone: '(555) 202-7890',
            role: 'admin',
            department: 'Administration',
            hireDate: new Date('2023-01-20').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2023-01-20').toISOString(),
            updatedAt: new Date('2023-01-20').toISOString(),
        },
        
        // Doctors (7)
        {
            firstName: 'Sarah',
            lastName: 'Johnson',
            email: 'sarah.johnson@clinic.com',
            phone: '(555) 301-1234',
            role: 'doctor',
            department: 'Cardiology',
            hireDate: new Date('2022-05-10').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-05-10').toISOString(),
            updatedAt: new Date('2022-05-10').toISOString(),
        },
        {
            firstName: 'Michael',
            lastName: 'Chen',
            email: 'michael.chen@clinic.com',
            phone: '(555) 302-5678',
            role: 'doctor',
            department: 'General Medicine',
            hireDate: new Date('2022-08-15').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-08-15').toISOString(),
            updatedAt: new Date('2022-08-15').toISOString(),
        },
        {
            firstName: 'Maria',
            lastName: 'Garcia',
            email: 'maria.garcia@clinic.com',
            phone: '(555) 303-9012',
            role: 'doctor',
            department: 'Pediatrics',
            hireDate: new Date('2023-02-01').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2023-02-01').toISOString(),
            updatedAt: new Date('2023-02-01').toISOString(),
        },
        {
            firstName: 'David',
            lastName: 'Wilson',
            email: 'david.wilson@clinic.com',
            phone: '(555) 304-3456',
            role: 'doctor',
            department: 'Orthopedics',
            hireDate: new Date('2022-11-08').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-11-08').toISOString(),
            updatedAt: new Date('2022-11-08').toISOString(),
        },
        {
            firstName: 'Rachel',
            lastName: 'Martinez',
            email: 'rachel.martinez@clinic.com',
            phone: '(555) 305-7890',
            role: 'doctor',
            department: 'Dermatology',
            hireDate: new Date('2023-04-12').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2023-04-12').toISOString(),
            updatedAt: new Date('2023-04-12').toISOString(),
        },
        {
            firstName: 'James',
            lastName: 'Anderson',
            email: 'james.anderson@clinic.com',
            phone: '(555) 306-1234',
            role: 'doctor',
            department: 'Neurology',
            hireDate: new Date('2022-09-22').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-09-22').toISOString(),
            updatedAt: new Date('2022-09-22').toISOString(),
        },
        {
            firstName: 'Amanda',
            lastName: 'Clark',
            email: 'amanda.clark@clinic.com',
            phone: '(555) 307-5678',
            role: 'doctor',
            department: 'Mental Health',
            hireDate: new Date('2023-06-05').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2023-06-05').toISOString(),
            updatedAt: new Date('2023-06-05').toISOString(),
        },
        
        // Nurses (5)
        {
            firstName: 'Emily',
            lastName: 'Rodriguez',
            email: 'emily.rodriguez@clinic.com',
            phone: '(555) 401-9012',
            role: 'nurse',
            department: 'Emergency',
            hireDate: new Date('2022-07-18').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-07-18').toISOString(),
            updatedAt: new Date('2022-07-18').toISOString(),
        },
        {
            firstName: 'Michelle',
            lastName: 'Brown',
            email: 'michelle.brown@clinic.com',
            phone: '(555) 402-3456',
            role: 'nurse',
            department: 'Cardiology',
            hireDate: new Date('2023-01-10').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2023-01-10').toISOString(),
            updatedAt: new Date('2023-01-10').toISOString(),
        },
        {
            firstName: 'Nicole',
            lastName: 'Taylor',
            email: 'nicole.taylor@clinic.com',
            phone: '(555) 403-7890',
            role: 'nurse',
            department: 'Pediatrics',
            hireDate: new Date('2022-10-05').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-10-05').toISOString(),
            updatedAt: new Date('2022-10-05').toISOString(),
        },
        {
            firstName: 'Kevin',
            lastName: 'White',
            email: 'kevin.white@clinic.com',
            phone: '(555) 404-1234',
            role: 'nurse',
            department: 'General Medicine',
            hireDate: new Date('2023-03-20').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2023-03-20').toISOString(),
            updatedAt: new Date('2023-03-20').toISOString(),
        },
        {
            firstName: 'Jessica',
            lastName: 'Lewis',
            email: 'jessica.lewis@clinic.com',
            phone: '(555) 405-5678',
            role: 'nurse',
            department: 'Orthopedics',
            hireDate: new Date('2022-12-08').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-12-08').toISOString(),
            updatedAt: new Date('2022-12-08').toISOString(),
        },
        
        // Receptionists (3)
        {
            firstName: 'Lisa',
            lastName: 'Park',
            email: 'lisa.park@clinic.com',
            phone: '(555) 501-9012',
            role: 'receptionist',
            department: 'Front Desk',
            hireDate: new Date('2022-06-12').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-06-12').toISOString(),
            updatedAt: new Date('2022-06-12').toISOString(),
        },
        {
            firstName: 'Ashley',
            lastName: 'Davis',
            email: 'ashley.davis@clinic.com',
            phone: '(555) 502-3456',
            role: 'receptionist',
            department: 'Front Desk',
            hireDate: new Date('2023-05-15').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2023-05-15').toISOString(),
            updatedAt: new Date('2023-05-15').toISOString(),
        },
        {
            firstName: 'Stephanie',
            lastName: 'Miller',
            email: 'stephanie.miller@clinic.com',
            phone: '(555) 503-7890',
            role: 'receptionist',
            department: 'Front Desk',
            hireDate: new Date('2022-09-30').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-09-30').toISOString(),
            updatedAt: new Date('2022-09-30').toISOString(),
        },
        
        // Managers (2)
        {
            firstName: 'Thomas',
            lastName: 'Harris',
            email: 'thomas.harris@clinic.com',
            phone: '(555) 601-1234',
            role: 'manager',
            department: 'Operations',
            hireDate: new Date('2022-04-25').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2022-04-25').toISOString(),
            updatedAt: new Date('2022-04-25').toISOString(),
        },
        {
            firstName: 'Catherine',
            lastName: 'Moore',
            email: 'catherine.moore@clinic.com',
            phone: '(555) 602-5678',
            role: 'manager',
            department: 'Patient Services',
            hireDate: new Date('2023-07-08').toISOString(),
            status: 'active',
            isActive: true,
            userId: null,
            createdAt: new Date('2023-07-08').toISOString(),
            updatedAt: new Date('2023-07-08').toISOString(),
        }
    ];

    await db.insert(staff).values(sampleStaff);
    
    console.log('✅ Staff seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});